// AUTO-GENERISANO iz docs/schema-rename-map.md + Prisma DMMF. Ne editovati rucno.
// Regenerisi skriptom scratchpad/gen-map.js. Tabela: 30.
//
// ⚠️ RUCNE IZMENE POSLE GENERISANJA (generator ih NE ZNA — ako se mapa ikad
// regenerise, ponovi ih; isti dug postoji od izbacivanja QBigTehn lanca i
// `T_Robna dokumenta` / `T_Robne stavke`):
//   • 26.07.2026 — izbacen `R_Tarife` → `tax_rates` (v. nadgrobnik ispod).
// Generator dobija guard iz docs/migration/BB_T_26-analiza-F2-mehanizam-sync.md
// (odbija emitovanje za tabele koje su presle u 3.0/4.0 vlasnistvo).
import type { TableMapping } from "./sync.types";

export const SYNC_MAP: TableMapping[] = [
  {
    source: "BBDefUser",
    model: "DefaultUser",
    targetDb: "default_users",
    pk: {
      kind: "single",
      field: "username",
    },
    watermark: null,
    columns: [
      {
        src: "UserName",
        field: "username",
        type: "String",
        nullable: false,
        isId: true,
      },
      {
        src: "DefaultGodina",
        field: "defaultYear",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "DefaultOJ",
        field: "defaultOrgUnitId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "DefaultOD",
        field: "defaultDepartmentId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "UnlockGodina",
        field: "unlockYear",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "UnlockOJ",
        field: "unlockOrgUnit",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "UnlockOD",
        field: "unlockDepartment",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "Level",
        field: "level",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "MaxLevel",
        field: "maxLevel",
        type: "Int",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "BBOdeljenja",
    model: "Department",
    targetDb: "departments",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "OD",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "OznakaOD",
        field: "code",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "OpisOD",
        field: "description",
        type: "String",
        nullable: false,
        isId: false,
      },
    ],
  },
  {
    source: "BBOrgJedinice",
    model: "OrganizationalUnit",
    targetDb: "organizational_units",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "OJ",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "OznakaOJ",
        field: "code",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "OpisOJ",
        field: "description",
        type: "String",
        nullable: false,
        isId: false,
      },
    ],
  },
  {
    source: "BBPravaPristupa",
    model: "AccessRight",
    targetDb: "access_rights",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "ID",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "ImeUsera",
        field: "username",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "ImeForme",
        field: "formName",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "ImeKontrole",
        field: "controlName",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Visible",
        field: "visible",
        type: "Boolean",
        nullable: false,
        isId: false,
      },
      {
        src: "Locked",
        field: "locked",
        type: "Boolean",
        nullable: false,
        isId: false,
      },
      {
        src: "Enabled",
        field: "enabled",
        type: "Boolean",
        nullable: false,
        isId: false,
      },
      {
        src: "Vrednost",
        field: "value",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "RecordSource",
        field: "recordSource",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Filter",
        field: "filter",
        type: "String",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "CFG_Global",
    model: "GlobalConfig",
    targetDb: "global_config",
    pk: {
      kind: "composite",
      fields: ["companyId", "parameter"],
      name: "companyId_parameter",
    },
    watermark: null,
    columns: [
      {
        src: "IDFirma",
        field: "companyId",
        type: "Int",
        nullable: false,
        isId: false,
      },
      {
        src: "Parametar",
        field: "parameter",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Vrednost",
        field: "value",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Tip",
        field: "type",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Opis",
        field: "description",
        type: "String",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "CFG_Sys",
    model: "SystemConfig",
    targetDb: "system_config",
    pk: {
      kind: "single",
      field: "parameter",
    },
    watermark: null,
    columns: [
      {
        src: "Parametar",
        field: "parameter",
        type: "String",
        nullable: false,
        isId: true,
      },
      {
        src: "Vrednost",
        field: "value",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Tip",
        field: "type",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Opis",
        field: "description",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "DIVUnos",
        field: "createdAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "Cenovnik",
    model: "PriceListEntry",
    targetDb: "price_list_entries",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "ID",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "Sifra artikla",
        field: "itemId",
        type: "Int",
        nullable: false,
        isId: false,
      },
      {
        src: "Vrsta dokumenta",
        field: "documentTypeId",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Cena",
        field: "price",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "Tarifa",
        field: "taxRateCode",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "CenaBezPDV",
        field: "priceWithoutVat",
        type: "Decimal",
        nullable: true,
        isId: false,
      },
      {
        src: "Taksa",
        field: "fee",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "Prn",
        field: "print",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "CenaSaPDV",
        field: "priceWithVat",
        type: "Decimal",
        nullable: true,
        isId: false,
      },
      {
        src: "CheckCenaSaPDV",
        field: "checkPriceWithVat",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "ZakCen",
        field: "isLocked",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "Info",
    model: "Notification",
    targetDb: "notifications",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "ID",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "DatumIVremeSlanja",
        field: "sentAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "KoJePoslao",
        field: "sentBy",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Prijem",
        field: "received",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "DatumIVremePrijema",
        field: "receivedAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "KoJePrimio",
        field: "receivedBy",
        type: "String",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "Komitenti",
    model: "Customer",
    targetDb: "customers",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: "updatedAt",
    columns: [
      {
        src: "Sifra",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "Naziv",
        field: "name",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Poslovnica",
        field: "branch",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Mesto",
        field: "city",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Adresa",
        field: "address",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Postanski broj",
        field: "postalCode",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Ziro racun_1",
        field: "bankAccount1",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Ziro racun_2",
        field: "bankAccount2",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Ziro racun_3",
        field: "bankAccount3",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Telefon",
        field: "phone",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Fax",
        field: "fax",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Kontakt",
        field: "contact",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Napomena",
        field: "note",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Drzava",
        field: "country",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Region",
        field: "region",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "Vrsta sifre",
        field: "codeTypeCode",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Email",
        field: "email",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Mobilni",
        field: "mobile",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Datum rodjenja",
        field: "birthDate",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "Web adresa",
        field: "webAddress",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Sifra prodavca",
        field: "salespersonId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "RabatKomitenta",
        field: "customerDiscount",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "ZastKodKupca",
        field: "buyerProtectionCode",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "PIB",
        field: "taxId",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "PDVStatus",
        field: "vatStatus",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "MSifra",
        field: "externalCode",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Odlozeno",
        field: "paymentTermDays",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "IDRuta",
        field: "routeId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "IDVozac",
        field: "driverId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "IDUplatniRacun",
        field: "paymentAccountId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "FakturisanjePoMestimaIsporuke",
        field: "invoicePerDeliveryAddress",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "Cenovnik",
        field: "priceListCode",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "PrviUnos",
        field: "createdAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "PoslednjaIzmena",
        field: "updatedAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "PrviUnosUser",
        field: "createdBy",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "PoslednjaIzmenaUser",
        field: "updatedBy",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "ProcenatProvizije",
        field: "commissionPercent",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "FiktRabatKomitenta",
        field: "fictitiousDiscount",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "KomitentiNacinPlacanja",
        field: "paymentMethod",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "PotpisKom",
        field: "signature",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "SkraceniNaziv",
        field: "shortName",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "DatumIVremeKom",
        field: "recordCreatedAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "ProveraDuga",
        field: "checkDebt",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "KreditLimit",
        field: "creditLimit",
        type: "Decimal",
        nullable: true,
        isId: false,
      },
      {
        src: "NeProveravajPIB",
        field: "skipTaxIdValidation",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "IDPantheon",
        field: "pantheonId",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "NewsLetter",
        field: "newsletter",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "PostaNaDruguAdresu",
        field: "mailToDifferentAddress",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "GLN",
        field: "gln",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "KLRucProc",
        field: "manualMarkupPercent",
        type: "Decimal",
        nullable: true,
        isId: false,
      },
      {
        src: "NapomenaZaSalda",
        field: "balanceNote",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "NePrikazatiUPregledu",
        field: "hideInOverview",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "JBKJS",
        field: "publicSectorId",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "MaticniBroj",
        field: "registrationNumber",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "ER_XMLSaPopustomPoArtiklu",
        field: "einvoiceXmlPerItemDiscount",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "CRF",
        field: "centralInvoiceRegistry",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "MRP_PotrebeStavke",
    model: "MrpDemandItem",
    targetDb: "mrp_demand_items",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "IDPotrebaStavka",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "IDPotreba",
        field: "demandId",
        type: "Int",
        nullable: false,
        isId: false,
      },
      {
        src: "IDCrtezIzvora",
        field: "sourceDrawingId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "IDCrtezNabavke",
        field: "procurementDrawingId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "SifraArtikla",
        field: "itemId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "KataloskiBrojStavka",
        field: "itemCatalogNumber",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "NazivArtiklaStavka",
        field: "itemName",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "JedinicaMereStavka",
        field: "itemUnit",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "IzvorStavke",
        field: "itemSource",
        type: "Int",
        nullable: false,
        isId: false,
      },
      {
        src: "KolicinaPotrebna",
        field: "requiredQuantity",
        type: "Decimal",
        nullable: false,
        isId: false,
      },
      {
        src: "DatumPotrebe",
        field: "demandDate",
        type: "DateTime",
        nullable: false,
        isId: false,
      },
      {
        src: "VremeIsporukeDana",
        field: "leadTimeDays",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "DatumNabavke",
        field: "procurementDate",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "Napomena",
        field: "note",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "DIVUnosa",
        field: "createdAt",
        type: "DateTime",
        nullable: false,
        isId: false,
      },
      {
        src: "DIVUnosaKorisnik",
        field: "createdBy",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "DIVIzmena",
        field: "updatedAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "DIVIzmenaKorisnik",
        field: "updatedBy",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "DobavljacID",
        field: "supplierId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "StatusStavke",
        field: "itemStatus",
        type: "Int",
        nullable: false,
        isId: false,
      },
      {
        src: "KolicinaRezervisano",
        field: "reservedQuantity",
        type: "Decimal",
        nullable: false,
        isId: false,
      },
      {
        src: "KolicinaZaNabavku",
        field: "toProcureQuantity",
        type: "Decimal",
        nullable: false,
        isId: false,
      },
    ],
  },
  {
    source: "MRP_StanjeArtikala",
    model: "MrpItemStock",
    targetDb: "mrp_item_stock",
    pk: {
      kind: "single",
      field: "itemId",
    },
    watermark: "updatedAt",
    columns: [
      {
        src: "SifraArtikla",
        field: "itemId",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "Zalihe",
        field: "inStock",
        type: "Decimal",
        nullable: false,
        isId: false,
      },
      {
        src: "Rezervisane",
        field: "reserved",
        type: "Decimal",
        nullable: false,
        isId: false,
      },
      {
        src: "Naziv",
        field: "name",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "KataloskiBroj",
        field: "catalogNumber",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "JedinicaMere",
        field: "unit",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "PoslednjaIzmena",
        field: "updatedAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "MRP_SyncStatus",
    model: "MrpSyncStatus",
    targetDb: "mrp_sync_status",
    pk: {
      kind: "single",
      field: "syncKey",
    },
    watermark: null,
    columns: [
      {
        src: "SyncKey",
        field: "syncKey",
        type: "String",
        nullable: false,
        isId: true,
      },
      {
        src: "PoslednjiSync",
        field: "lastSyncedAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "PoslednjiSyncKorisnik",
        field: "lastSyncedBy",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Napomena",
        field: "note",
        type: "String",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "Magacini",
    model: "Warehouse",
    targetDb: "warehouses",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "IDFirma",
        field: "companyId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "IDMagacin",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "Magacin",
        field: "name",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "UlicaIBroj",
        field: "street",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Mesto",
        field: "city",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "ProsecneCene",
        field: "averagePrices",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "VrstaMag",
        field: "warehouseType",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "KontoMag",
        field: "account",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "ImeMagacionera",
        field: "managerName",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "BrLkMagacionera",
        field: "managerIdNumber",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "PotpisSlika",
        field: "signatureImagePath",
        type: "String",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "Parametri za rad",
    model: "WorkParameter",
    targetDb: "work_parameters",
    pk: {
      kind: "single",
      field: "username",
    },
    watermark: null,
    columns: [
      {
        src: "Korisnik",
        field: "username",
        type: "String",
        nullable: false,
        isId: true,
      },
      {
        src: "VrstaDokumenta",
        field: "documentType",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Telefon",
        field: "phone",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Poslednji broj fakture",
        field: "lastInvoiceNumber",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "Poslednji broj profakture",
        field: "lastProformaNumber",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "Faktura kroz",
        field: "invoiceThrough",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Profaktura kroz",
        field: "proformaThrough",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Faktura prefix",
        field: "invoicePrefix",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Profaktura prefix",
        field: "proformaPrefix",
        type: "String",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "Predmeti",
    model: "Project",
    targetDb: "projects",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "IDPredmet",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "BrojPredmeta",
        field: "projectNumber",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Opis",
        field: "description",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "DatumOtvaranja",
        field: "openedAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "IDProdavac",
        field: "salespersonId",
        type: "Int",
        nullable: false,
        isId: false,
      },
      {
        src: "IDKomitent",
        field: "customerId",
        type: "Int",
        nullable: false,
        isId: false,
      },
      {
        src: "NextAction",
        field: "nextAction",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "DatumZakljucenja",
        field: "closedAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "Memo",
        field: "memo",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Status",
        field: "status",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "NasaRef",
        field: "ourRef",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "NasKontakt1",
        field: "ourContact1",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "NasKontakt2",
        field: "ourContact2",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "NasTel1",
        field: "ourPhone1",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "NasTel2",
        field: "ourPhone2",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "VasaRef",
        field: "theirRef",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "VasKontakt1",
        field: "theirContact1",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "VasKontakt2",
        field: "theirContact2",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "VasTel1",
        field: "theirPhone1",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "VasTel2",
        field: "theirPhone2",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "NabavnaVrednost",
        field: "procurementValue",
        type: "Decimal",
        nullable: true,
        isId: false,
      },
      {
        src: "Carina",
        field: "customs",
        type: "Decimal",
        nullable: true,
        isId: false,
      },
      {
        src: "Spedicija",
        field: "forwarding",
        type: "Decimal",
        nullable: true,
        isId: false,
      },
      {
        src: "Prevoz",
        field: "transport",
        type: "Decimal",
        nullable: true,
        isId: false,
      },
      {
        src: "Ostalo",
        field: "other",
        type: "Decimal",
        nullable: true,
        isId: false,
      },
      {
        src: "InoDobavljac",
        field: "foreignSupplierId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "RJ",
        field: "workUnitCode",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "devvaluta",
        field: "currency",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "kurs",
        field: "exchangeRate",
        type: "Decimal",
        nullable: true,
        isId: false,
      },
      {
        src: "IDVrstaPosla",
        field: "workTypeId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "NazivPredmeta",
        field: "projectName",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "RokZavrsetka",
        field: "deadline",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "Potpis",
        field: "signature",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "DatumIVreme",
        field: "createdAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "BrojUgovora",
        field: "contractNumber",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "DatumUgovora",
        field: "contractDate",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "BrojNarudzbenice",
        field: "orderNumber",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "DatumNarudzbenice",
        field: "orderDate",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "Prodavci",
    model: "Salesperson",
    targetDb: "salespeople",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "Sifra prodavca",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "Prodavac",
        field: "name",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Region",
        field: "region",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "ProcenatZaObracun",
        field: "commissionPercent",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "DeljivoUGrupi",
        field: "splitInTeam",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "ImeProdavca",
        field: "firstName",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "BrLkProdavca",
        field: "idNumber",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "LogAcc",
        field: "loginAccount",
        type: "String",
        nullable: true,
        isId: false,
      },
      // "Password" → password NAMERNO IZBAČEN (DB audit DB-049): plaintext legacy
      // lozinke se ne preslikavaju u 3.0 bazu — 3.0 ih nigde ne koristi, a svaki
      // dump bi ih raznosio. Pri eventualnoj regeneraciji mape ovo isključenje
      // MORA da se ponovi (kolona salespeople.password je isprazjnjena na produ).
      {
        src: "Aktivan",
        field: "active",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "NefiskalniRN",
        field: "nonFiscalWorkOrder",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "Storniranje",
        field: "canCancel",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "PotpisSlika",
        field: "signatureImage",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "OznakaTima",
        field: "teamCode",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Telefon",
        field: "phone",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Email",
        field: "email",
        type: "String",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "R_Artikli",
    model: "Item",
    targetDb: "items",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "Sifra artikla",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "Kataloski broj",
        field: "catalogNumber",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "BarKod",
        field: "barCode",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "PLU",
        field: "plu",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "ExtSifra",
        field: "externalCode",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Naziv",
        field: "name",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Jedinica mere",
        field: "unit",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Pakovanje",
        field: "packaging",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "InoJm",
        field: "foreignUnit",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Kutija",
        field: "box",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "Transportno pakovanje",
        field: "transportPackaging",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "Poreklo",
        field: "originCode",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Grupa",
        field: "groupCode",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Podgrupa",
        field: "subgroupCode",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Tarifa robe",
        field: "goodsTaxRateCode",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Tarifa usluga",
        field: "serviceTaxRateCode",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Uvek porez na robu",
        field: "alwaysTaxGoods",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "Uvek porez na usluge",
        field: "alwaysTaxServices",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "VP cena",
        field: "wholesalePrice",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "MP cena",
        field: "retailPrice",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "NabDevCena",
        field: "fxPurchasePrice",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "ProdDevCena",
        field: "fxSalePrice",
        type: "Float",
        nullable: true,
        isId: false,
      },
      // ┌────────────────────────────────────────────────────────────────────┐
      // │ MINIMALNA KOLIČINA — VLASNIK JE BigBit DO PRELASKA (01.04.2027)    │
      // └────────────────────────────────────────────────────────────────────┘
      // Ova kolona je 06.08.2026. bila IZBAČENA iz mape (commit `b2d11e8c`), pa
      // ISTOG DANA VRAĆENA — vlasnik je ispravio odluku: „ovde nema UNOSA dok ne
      // krenemo da radimo sa APP. Rekli smo da ćemo samo čitati podatke iz BigBita."
      //
      // ZAŠTO JE VRAĆANJE BILO OBAVEZNO, a ne samo formalnost: dok je kolona bila
      // van mape, noćni uvoz je prestao da je puni, a NIKO je nije unosio ovde (unos
      // nije pušten u rad). Kolona bi ostala zamrznuta na 162 vrednosti od 06.08. i
      // tiho zastarevala mesecima — ništa ne bi puklo, podatak bi samo prestao da
      // bude istinit. Izmereno na produkciji 06.08.2026, PRE noćnog uvoza u 03:45:
      // 162 artikla ≠ 0, 92.460 nula, 3 prazno (od 92.625) — ništa nije izgubljeno.
      //
      // 🔴 PRISUSTVO OVE KOLONE OVDE NIJE SLOBODNA ODLUKA. Ono je IZVEDENO iz
      // jednog jedinog prekidača: `VLASNIK_MINIMALNE_KOLICINE` u
      // `masters/items.write-policy.ts` (danas `"BigBit"`). Iz istog prekidača sledi
      // i da `PATCH /v1/artikli/:id/minimalna-kolicina` ODBIJA upis. Brana
      // `masters/items.minimalna-kolicina-prekidac.spec.ts` pada ako se ovo dvoje
      // raziđe u BILO KOM smeru — dakle i ako neko izbaci kolonu odavde a ostavi
      // prekidač na `"BigBit"`, i obrnuto.
      //
      // 01.04.2027 (prelazak na 4.0 kao izvor istine): prekidač ide na `"4.0"` I
      // ovaj blok se briše — jedno bez drugog obara test.
      {
        src: "Minimalna kolicina",
        field: "minQuantity",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "ArtTaksa",
        field: "itemFee",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "Odlozeno",
        field: "paymentTermDays",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "Neoporezivi deo",
        field: "nonTaxablePart",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "MaxRabatProc",
        field: "maxDiscountPercent",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "Memo",
        field: "memo",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "KngSifra",
        field: "accountingCode",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "ArtAkciza",
        field: "itemExcise",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "KngSifra_2",
        field: "accountingCode2",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "ZavTrosProiz",
        field: "finalProcessingCost",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "CarStopa",
        field: "customsRate",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "IDRaster",
        field: "rasterId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "CarTarifa",
        field: "customsTariff",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "ZemljaPorekla",
        field: "originCountry",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Polica",
        field: "shelf",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "INONaziv",
        field: "foreignName",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "SifDob",
        field: "supplierId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "WebOpis",
        field: "webDescription",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "OpisArtikla",
        field: "itemDescription",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Tezina",
        field: "weight",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "PDFLink",
        field: "pdfLink",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "ZaBrisanje",
        field: "toDelete",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "Aktivan",
        field: "active",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "CenaZaUpisUCen",
        field: "priceToWritePricelist",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "IDMestoIzdavanja",
        field: "issuePlaceId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "Proizvodjac",
        field: "manufacturer",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "HPS",
        field: "hps",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "PotpisArt",
        field: "signature",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "DatumIVremeArt",
        field: "createdAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "KolUPak",
        field: "quantityInPackage",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "KLRucProc",
        field: "manualMarkupPercent",
        type: "Decimal",
        nullable: true,
        isId: false,
      },
      {
        src: "OsnJM",
        field: "baseUnit",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "SlikaSimbolaLink",
        field: "symbolImageLink",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "MPKaloProc",
        field: "retailLossPercent",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "WordLokacija",
        field: "wordLocation",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "VPKaloProc",
        field: "wholesaleLossPercent",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "NeVodiZalihe",
        field: "notStockTracked",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "TezinaKg",
        field: "weightKg",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "Zapremina",
        field: "volume",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "Povrsina",
        field: "area",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "RSort",
        field: "sortOrder",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "AkcijskiRabat",
        field: "promotionDiscount",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "Napomena2",
        field: "note2",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "IDKvalitetArtikla",
        field: "qualityTypeId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "Debljina",
        field: "thickness",
        type: "Float",
        nullable: true,
        isId: false,
      },
      {
        src: "BBSifra artikla",
        field: "externalItemId",
        type: "Int",
        nullable: false,
        isId: false,
      },
    ],
  },
  // NADGROBNIK — `R_Tarife` → `tax_rates` UKLONJEN IZ MAPE 26.07.2026 (presuda
  // Nenada: registar PDV tarifa se od sada vodi ISKLJUČIVO u 4.0, POST/PATCH
  // /api/v1/pdv/tax-rates). Isti postupak kao sa `T_Robna dokumenta` /
  // `T_Robne stavke`: strategija je bila full refresh (deleteMany + reinsert), pa
  // bi svaki sync — i ručni „sync all" i noćni posao — obrisao svaku 4.0-unesenu
  // tarifu. `tax_rates` je od sada u OWNED_PRODUCTION_TABLES (table-ownership.ts)
  // kao zaštita ako se mapiranje ikad vrati. NE VRAĆATI bez odluke o vlasništvu.
  {
    source: "R_Vrste dokumenata",
    model: "DocumentType",
    targetDb: "document_types",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "ID",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "Vrsta dokumenta",
        field: "code",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Opis",
        field: "description",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Ulazni",
        field: "isInbound",
        type: "Boolean",
        nullable: false,
        isId: false,
      },
      {
        src: "Analiticki konto",
        field: "analyticalAccount",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Knjiziti analitiku",
        field: "postAnalytical",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "Sema za kontiranje",
        field: "postingTemplate",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "Knjiziti sintetiku",
        field: "postSynthetic",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "Prodaja sa PPP",
        field: "saleWithPpp",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "Prodaja sa PPU",
        field: "saleWithPpu",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "KnjizitiTKZad",
        field: "postRetailCharge",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "KnjizitiTKRazd",
        field: "postRetailDischarge",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "TextZaReport",
        field: "reportText",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "KnjizitiUPDVEvidenciju",
        field: "postInVatLedger",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "KEPUDefZaduzenje",
        field: "kepuDefaultCharge",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "KEPUDefRazduzenje",
        field: "kepuDefaultDischarge",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "InterniDokument",
        field: "isInternalDocument",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "NumeracijaOd",
        field: "numberingStart",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "KOTP",
        field: "isFiscal",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "PrefiksBrojaDok",
        field: "documentNumberPrefix",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "IDMagacinZaVrstuDok",
        field: "defaultWarehouseId",
        type: "Int",
        nullable: true,
        isId: false,
      },
      {
        src: "KODJ",
        field: "isDepartmental",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "FR",
        field: "isFr",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
      {
        src: "UticeNaZalihe",
        field: "affectsStock",
        type: "Boolean",
        nullable: true,
        isId: false,
      },
    ],
  },
  // ┌───────────────────────────────────────────────────────────────────────┐
  // │ MATIČNI PODACI FIRME — 4.0 JE VLASNIK (odluka Nenad, 05.08.2026)      │
  // └───────────────────────────────────────────────────────────────────────┘
  // Mapiranje `Radni fajlovi` → `companies` (516 redova mape, 100+ kolona) je
  // IZBAČENO, istim postupkom kao ranije `R_Tarife` i `goods_documents`.
  //
  // POVOD: 03.08.2026. su podaci firme upisani na produkciju (adresa, PIB, matični
  // broj, tekući račun, telefon, APR rečenica) i posle deploy-a POTVRĐENI. Do 05.08.
  // su NESTALI — ostao je samo poštanski broj (nova kolona koju izvor ne zna) i
  // IBAN/SWIFT (zaštićeni kroz `NATIVE_COLUMN_TABLES`). Sve ostalo je bilo MAPIRANO,
  // pa ga je sync prepisao onim što stoji u izvoru — a tamo je prazno. Upis kroz SQL
  // zato nije ni imao šanse da preživi; popravka nije ponovni upis nego vlasništvo.
  //
  // ZAŠTO VLASNIŠTVO, A NE UNOS U BIGBIT: identitet firme ne treba da drži sistem
  // koji se gasi 01.04.2027. Uz to je ovo preduslov da program uopšte može da se
  // instalira kod druge firme — tamo BigBita nema, pa se podaci (uključujući logotip)
  // unose kroz Podešavanja → Firma. Od sada je taj ekran JEDINI izvor.
  //
  // ⚠️ `companies` je i u `OWNED_PRODUCTION_TABLES` — ako se mapiranje ikad vrati,
  // generički syncer odbija destruktivan full-refresh dok tabela ima redova.
  {
    source: "RobnaDokumentaMirror",
    model: "GoodsDocumentMirror",
    targetDb: "goods_documents_mirror",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "IDDok",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "VrstaDokumenta",
        field: "documentType",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "DatumDokumenta",
        field: "documentDate",
        type: "DateTime",
        nullable: false,
        isId: false,
      },
    ],
  },
  {
    source: "RobneStavkeMirror",
    model: "GoodsDocumentItemMirror",
    targetDb: "goods_document_items_mirror",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: "updatedAt",
    columns: [
      {
        src: "IDStavke",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "IDDok",
        field: "documentId",
        type: "Int",
        nullable: false,
        isId: false,
      },
      {
        src: "SifraArtikla",
        field: "itemId",
        type: "Int",
        nullable: false,
        isId: false,
      },
      {
        src: "KataloskiBroj",
        field: "catalogNumber",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "IDMagacin",
        field: "warehouseId",
        type: "Int",
        nullable: false,
        isId: false,
      },
      {
        src: "KolicinaUlaz",
        field: "quantityIn",
        type: "Decimal",
        nullable: false,
        isId: false,
      },
      {
        src: "KolicinaIzlaz",
        field: "quantityOut",
        type: "Decimal",
        nullable: false,
        isId: false,
      },
      {
        src: "PoslednjaIzmena",
        field: "updatedAt",
        type: "DateTime",
        nullable: false,
        isId: false,
      },
    ],
  },
  {
    source: "UplatniRacuni",
    model: "PaymentAccount",
    targetDb: "payment_accounts",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "IDFirma",
        field: "companyId",
        type: "Int",
        nullable: false,
        isId: false,
      },
      {
        src: "ID",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "UplatniRacun",
        field: "accountNumber",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "NazivBanke",
        field: "bankName",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Default",
        field: "isDefault",
        type: "Boolean",
        nullable: false,
        isId: false,
      },
      {
        src: "Rbr",
        field: "sortOrder",
        type: "Int",
        nullable: false,
        isId: false,
      },
      {
        src: "KodZemlje",
        field: "countryCode",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "OznakaBanke",
        field: "bankCode",
        type: "String",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "Vrste sifara",
    model: "CodeType",
    targetDb: "code_types",
    pk: {
      kind: "single",
      field: "code",
    },
    watermark: null,
    columns: [
      {
        src: "Vrsta sifre",
        field: "code",
        type: "String",
        nullable: false,
        isId: true,
      },
      {
        src: "Opis",
        field: "description",
        type: "String",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "_Dnevnik",
    model: "Journal",
    targetDb: "journal",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "ID",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "Opis",
        field: "message",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "DIV",
        field: "createdAt",
        type: "DateTime",
        nullable: false,
        isId: false,
      },
    ],
  },
  {
    source: "_RegAccess",
    model: "AppAccessLog",
    targetDb: "app_access_log",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "ID",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "HDSn",
        field: "hardwareId",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "WinUser",
        field: "windowsUser",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "ComputerName",
        field: "computerName",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "IPAdress",
        field: "ipAddress",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Program_Name",
        field: "programName",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "CNNString",
        field: "connectionString",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Login_Time",
        field: "loginAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "_RegApps",
    model: "RegisteredApp",
    targetDb: "registered_apps",
    pk: {
      kind: "single",
      field: "appName",
    },
    watermark: "updatedAt",
    columns: [
      {
        src: "DBName",
        field: "databaseName",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "AppName",
        field: "appName",
        type: "String",
        nullable: false,
        isId: true,
      },
      {
        src: "Disabled",
        field: "disabled",
        type: "Boolean",
        nullable: false,
        isId: false,
      },
      {
        src: "AplFile",
        field: "appFile",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "MDWFile",
        field: "mdwFile",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "ClientDir",
        field: "clientDir",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "DownloadDir",
        field: "downloadDir",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "PrviUnos",
        field: "createdAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "PoslednjaIzmena",
        field: "updatedAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "_RegAppsFiles",
    model: "RegisteredAppFile",
    targetDb: "registered_app_files",
    pk: {
      kind: "composite",
      fields: ["appName", "fileName"],
      name: "appName_fileName",
    },
    watermark: "updatedAt",
    columns: [
      {
        src: "DBName",
        field: "databaseName",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "AppName",
        field: "appName",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "AppFileName",
        field: "fileName",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "ClientDir",
        field: "clientDir",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Install",
        field: "install",
        type: "Boolean",
        nullable: false,
        isId: false,
      },
      {
        src: "Update",
        field: "update",
        type: "Boolean",
        nullable: false,
        isId: false,
      },
      {
        src: "PrviUnos",
        field: "createdAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "PoslednjaIzmena",
        field: "updatedAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "_RegUsers",
    model: "RegisteredUser",
    targetDb: "registered_users",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: "updatedAt",
    columns: [
      {
        src: "DBName",
        field: "databaseName",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "RegUserID",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "Disabled",
        field: "disabled",
        type: "Boolean",
        nullable: false,
        isId: false,
      },
      {
        src: "HDSn",
        field: "hardwareId",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "WinUser",
        field: "windowsUser",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "ComputerName",
        field: "computerName",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "IPAdress",
        field: "ipAddress",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Name",
        field: "fullName",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "email",
        field: "email",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Telefon",
        field: "phone",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Opis",
        field: "description",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "VaziOdDatuma",
        field: "validFrom",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "VaziDoDatuma",
        field: "validTo",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "PrviUnos",
        field: "createdAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "PoslednjaIzmena",
        field: "updatedAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "_RegUsersApps",
    model: "RegisteredUserApp",
    targetDb: "registered_user_apps",
    pk: {
      kind: "composite",
      fields: ["userId", "appName"],
      name: "userId_appName",
    },
    watermark: "updatedAt",
    columns: [
      {
        src: "DBName",
        field: "databaseName",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "RegUserID",
        field: "userId",
        type: "Int",
        nullable: false,
        isId: false,
      },
      {
        src: "AppName",
        field: "appName",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Disabled",
        field: "disabled",
        type: "Boolean",
        nullable: false,
        isId: false,
      },
      {
        src: "BBUserName",
        field: "bbUserName",
        type: "String",
        nullable: true,
        isId: false,
      },
      // "BBPassword" → bbPassword NAMERNO IZBAČEN (DB audit DB-049) — kao
      // salespeople.password gore; kolona registered_user_apps.bb_password
      // ispražnjena na produ, isključenje ponoviti pri regeneraciji mape.
      {
        src: "BBMacroName",
        field: "bbMacroName",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "EXCL",
        field: "excl",
        type: "Boolean",
        nullable: false,
        isId: false,
      },
      {
        src: "RUNTIME",
        field: "runtime",
        type: "Boolean",
        nullable: false,
        isId: false,
      },
      {
        src: "BBExtraStartUp",
        field: "bbExtraStartUp",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "BBCMD",
        field: "bbCmd",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "PrviUnos",
        field: "createdAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
      {
        src: "PoslednjaIzmena",
        field: "updatedAt",
        type: "DateTime",
        nullable: true,
        isId: false,
      },
    ],
  },
  {
    source: "_Rev",
    model: "AppRevision",
    targetDb: "app_revisions",
    pk: {
      kind: "single",
      field: "id",
    },
    watermark: null,
    columns: [
      {
        src: "ID",
        field: "id",
        type: "Int",
        nullable: false,
        isId: true,
      },
      {
        src: "APP",
        field: "app",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Ver",
        field: "version",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "VerDatum",
        field: "versionDate",
        type: "DateTime",
        nullable: false,
        isId: false,
      },
      {
        src: "Tema",
        field: "topic",
        type: "String",
        nullable: false,
        isId: false,
      },
      {
        src: "Opis",
        field: "description",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "Uradjeno",
        field: "isDone",
        type: "Boolean",
        nullable: false,
        isId: false,
      },
      {
        src: "Firma",
        field: "company",
        type: "String",
        nullable: true,
        isId: false,
      },
      {
        src: "DIVUnos",
        field: "createdAt",
        type: "DateTime",
        nullable: false,
        isId: false,
      },
      {
        src: "SubRev",
        field: "subRevision",
        type: "Int",
        nullable: false,
        isId: false,
      },
    ],
  },
];
