-- ============================================================================
-- TRAG FORSIRANE FINALIZACIJE ZAVRŠNOG RAČUNA (stavka B, 28.07.2026)
-- ============================================================================
-- ZAŠTO
--   `POST /v1/zavrsni/statements/:id/finalize {force:true}` je do sada TIHO gasio
--   SVA kontrolna pravila: obračun bi prešao u FINALIZED, a nigde — ni u bazi, ni u
--   odgovoru, ni na ekranu — ne bi ostalo traga da ijedna kontrola nije prošla.
--   U praksi je forsiranje bilo RUTINSKO, jer je jedino netautološko pravilo
--   (aktiva = pasiva) padalo zbog 13 zatečenih neuravnoteženih naloga iz BigBita
--   (Σduguje − Σpotražuje = 0,10 RSD), pa je knjigovođa svaki put gazio i preostalih
--   šest. Nezavisan pregled 28.07. (nalazi V1 i S3) traži da se forsiranje BELEŽI
--   (ko, kada, koja pravila su pala) i da se VIDI na obračunu.
--
-- ŠTA OVA MIGRACIJA RADI
--   Uvodi `statement_control_overrides` — po jedan red za SVAKU forsiranu
--   finalizaciju (tabela je istorija, ne stanje). `ControlRulesService.evaluateControls`
--   te redove čita i vraća ih kao pseudo-pravilo `FORSIRANA_FINALIZACIJA` u istom
--   odgovoru kao i prava pravila, pa se forsiranje vidi na postojećem ekranu kontrola
--   bez ijedne izmene na frontendu.
--
-- ŠTA OVA MIGRACIJA NE RADI
--   Ne dira nijedan postojeći red i nijednu postojeću tabelu — nema DELETE, nema
--   UPDATE, nema promene tipa. Ponovno pokretanje je no-op (`IF NOT EXISTS`).
--   Ne uvodi ni jedan constraint nad `financial_statements` osim FK-a sa CASCADE:
--   brisanje obračuna (koje aplikacija ionako ne nudi) briše i njegov trag, jer trag
--   bez obračuna nema značenje.
--
-- ZAŠTO jsonb A NE ZASEBNA TABELA STAVKI
--   Snimak kontrola je DOKAZ U TRENUTKU FORSIRANJA i mora ostati nepromenjen i kad se
--   katalog pravila kasnije izmeni. Normalizovana tabela bi ga vezala za današnje
--   šifre pravila; jsonb ga čuva doslovno onako kako je korisnik video.
-- ============================================================================

CREATE TABLE IF NOT EXISTS "statement_control_overrides" (
  "id"                INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  "statement_id"      INTEGER      NOT NULL,
  -- meki ref users.id (konvencija repoa: bez FK na users)
  "forced_by_user_id" INTEGER,
  -- e-mail se snima DENORMALIZOVANO: trag mora biti čitljiv i kad korisnik nestane
  "forced_by_email"   VARCHAR(255),
  "forced_at"         TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- pravila koja su PALA i time blokirala finalizaciju: [{code,name,left,right,diff,message}]
  "failed_rules"      JSONB        NOT NULL,
  -- snimak SVIH pravila u trenutku forsiranja (uključujući upozorenja i prošla)
  "control_snapshot"  JSONB        NOT NULL,
  -- obrazloženje korisnika; danas se ne traži kroz API, polje čeka izmenu ekrana
  "reason"            VARCHAR(500),
  CONSTRAINT "pk_statement_control_overrides" PRIMARY KEY ("id"),
  CONSTRAINT "fk_statement_control_overrides_statement"
    FOREIGN KEY ("statement_id") REFERENCES "financial_statements" ("id")
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS "idx_statement_control_overrides_statement"
  ON "statement_control_overrides" ("statement_id", "forced_at" DESC);
