#!/usr/bin/env python3
"""
Konvertuje SSMS schema dump (T-SQL) u PostgreSQL DDL – tabele, kolone, PK,
podrazumevane vrednosti (ALTER), strani ključevi. Bez stored procedura/funkcija.

Legacy jednokratni alat: izvor istine za šemu je prisma/schema.prisma + prisma/migrations.
Ovaj skript ostaje samo ako ponovo uvozite dump iz SQL Servera; posle toga uraditi
`prisma db pull` ili ručno uskladiti migracije.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SRC = _REPO_ROOT / "schema" / "script.sql"
OUT = _REPO_ROOT / "legacy" / "schema-baseline-from-mssql.sql"

WS_WITH = re.compile(
    r"\s*WITH\s*\(\s*PAD_INDEX\s*=\s*OFF\s*,\s*STATISTICS_NORECOMPUTE\s*=\s*OFF\s*,"
    r"\s*IGNORE_DUP_KEY\s*=\s*OFF\s*,\s*ALLOW_ROW_LOCKS\s*=\s*ON\s*,\s*ALLOW_PAGE_LOCKS\s*=\s*ON\s*\)",
    re.I,
)

# Prvi tip token na liniji kolone (posle konverzije u PG DDL)
COL_LINE_RE = re.compile(
    r'^\s*"([^"]+)"\s+'
    r"(DOUBLE\s+PRECISION|BOOLEAN|INTEGER|BIGINT|SMALLINT|TEXT|DATE|TIME|BYTEA|UUID|XML|"
    r"REAL|NUMERIC\(\d+\s*,\s*\d+\)|VARCHAR\(\d+\)|CHAR\(\d+\)|"
    r"TIMESTAMP(?:\(\d+\))?)\b",
    re.I,
)


def split_go_batches(text: str) -> list[str]:
    parts = re.split(r"^\s*GO\s*$", text, flags=re.I | re.M)
    return [p.strip() for p in parts if p.strip()]


def batch_to_single_line_preserve_brackets(batch: str) -> str:
    """
    Spaja redove u jedan red. Ne koristiti ' '.join(batch.split()) jer split()
    deli na svaki razmak i gubi višestruke razmake unutar [identifikatora].
    """
    parts = [ln.strip() for ln in batch.splitlines() if ln.strip()]
    return " ".join(parts)


def qident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def convert_bracket_idents(s: str) -> str:
    return re.sub(r"\[([^\]]+)\]", lambda m: qident(m.group(1)), s)


def strip_sql_server_index_options(s: str) -> str:
    s = re.sub(r"\bNONCLUSTERED\b", "", s, flags=re.I)
    s = re.sub(r"\bCLUSTERED\b", "", s, flags=re.I)
    s = WS_WITH.sub("", s)
    s = re.sub(r"\s+ASC\b", "", s, flags=re.I)
    s = re.sub(r"\s+DESC\b", " DESC", s, flags=re.I)
    s = re.sub(r"\s+ON\s+(\[PRIMARY\]|\"PRIMARY\")", "", s, flags=re.I)
    s = re.sub(r"\s*TEXTIMAGE_ON\s+(\[PRIMARY\]|\"PRIMARY\")", "", s, flags=re.I)
    return s


def convert_computed_datum_nabavke(line: str) -> str | None:
    if "dateadd" not in line.lower():
        return None
    # Jedina izvedena kolona u šemi
    if re.search(r"\[DatumNabavke\].*dateadd", line, re.I):
        return (
            '\t"DatumNabavke" DATE GENERATED ALWAYS AS '
            '(("DatumPotrebe" - COALESCE("VremeIsporukeDana", 0))) STORED'
        )
    return None


def convert_mssql_types(fragment: str) -> str:
    s = fragment

    # IDENTITY (samo (1,1) u ovoj bazi)
    s = re.sub(
        r"\[bigint\]\s+IDENTITY\s*\(\s*\d+\s*,\s*\d+\s*\)",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY",
        s,
        flags=re.I,
    )
    s = re.sub(
        r"\[int\]\s+IDENTITY\s*\(\s*\d+\s*,\s*\d+\s*\)",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY",
        s,
        flags=re.I,
    )
    s = re.sub(
        r"\[smallint\]\s+IDENTITY\s*\(\s*\d+\s*,\s*\d+\s*\)",
        "SMALLINT GENERATED BY DEFAULT AS IDENTITY",
        s,
        flags=re.I,
    )

    s = re.sub(
        r"\[decimal\]\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)",
        r"NUMERIC(\1,\2)",
        s,
        flags=re.I,
    )
    s = re.sub(
        r"\[numeric\]\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)",
        r"NUMERIC(\1,\2)",
        s,
        flags=re.I,
    )
    s = re.sub(r"\[datetime2\]\s*\(\s*(\d+)\s*\)", r"TIMESTAMP(\1)", s, flags=re.I)
    s = re.sub(r"\[datetime2\]", "TIMESTAMP", s, flags=re.I)
    s = re.sub(r"\[datetime\]", "TIMESTAMP", s, flags=re.I)
    s = re.sub(r"\[smalldatetime\]", "TIMESTAMP", s, flags=re.I)
    s = re.sub(r"\[date\]", "DATE", s, flags=re.I)
    s = re.sub(r"\[time\](?:\s*\(\s*\d+\s*\))?", "TIME", s, flags=re.I)

    s = re.sub(r"\[nvarchar\]\s*\(\s*max\s*\)", "TEXT", s, flags=re.I)
    s = re.sub(r"\[varchar\]\s*\(\s*max\s*\)", "TEXT", s, flags=re.I)
    s = re.sub(r"\[nvarchar\]\s*\(\s*(\d+)\s*\)", r"VARCHAR(\1)", s, flags=re.I)
    s = re.sub(r"\[varchar\]\s*\(\s*(\d+)\s*\)", r"VARCHAR(\1)", s, flags=re.I)
    s = re.sub(r"\[nchar\]\s*\(\s*(\d+)\s*\)", r"CHAR(\1)", s, flags=re.I)
    s = re.sub(r"\[char\]\s*\(\s*(\d+)\s*\)", r"CHAR(\1)", s, flags=re.I)

    s = re.sub(r"\[ntext\]", "TEXT", s, flags=re.I)
    s = re.sub(r"\[text\]", "TEXT", s, flags=re.I)
    s = re.sub(r"\[image\]", "BYTEA", s, flags=re.I)
    s = re.sub(r"\[varbinary\]\s*\(\s*max\s*\)", "BYTEA", s, flags=re.I)
    s = re.sub(r"\[varbinary\]\s*\(\s*\d+\s*\)", "BYTEA", s, flags=re.I)
    s = re.sub(r"\[binary\]\s*\(\s*\d+\s*\)", "BYTEA", s, flags=re.I)

    s = re.sub(r"\[uniqueidentifier\]", "UUID", s, flags=re.I)
    s = re.sub(r"\[xml\]", "XML", s, flags=re.I)
    s = re.sub(r"\[money\]", "NUMERIC(19,4)", s, flags=re.I)
    s = re.sub(r"\[smallmoney\]", "NUMERIC(10,4)", s, flags=re.I)
    s = re.sub(r"\[float\]", "DOUBLE PRECISION", s, flags=re.I)
    s = re.sub(r"\[real\]", "REAL", s, flags=re.I)
    s = re.sub(r"\[bit\]", "BOOLEAN", s, flags=re.I)
    s = re.sub(r"\[tinyint\]", "SMALLINT", s, flags=re.I)
    s = re.sub(r"\[bigint\]", "BIGINT", s, flags=re.I)
    s = re.sub(r"\[smallint\]", "SMALLINT", s, flags=re.I)
    s = re.sub(r"\[int\]", "INTEGER", s, flags=re.I)

    return s


def extract_create_table_blocks(content: str) -> list[tuple[str, str]]:
    """Vraća listu (table_name_unquoted, inner_sql_before_paren_fix)."""
    results: list[tuple[str, str]] = []
    i = 0
    while True:
        m = re.search(r"CREATE\s+TABLE\s+\[dbo\]\.\[([^\]]+)\]\s*\(", content[i:], re.I)
        if not m:
            break
        start = i + m.start()
        table_name = m.group(1)
        start_paren = i + m.end() - 1  # pozicija '('

        depth = 0
        j = start_paren
        while j < len(content):
            c = content[j]
            if c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    inner = content[start_paren + 1 : j]
                    results.append((table_name, inner))
                    i = j + 1
                    break
            j += 1
        else:
            break
    return results


def collect_column_pg_types(
    table_name: str, inner_pg: str, acc: dict[tuple[str, str], str]
) -> None:
    for line in inner_pg.splitlines():
        s = line.strip()
        if not s or s.upper().startswith("CONSTRAINT"):
            continue
        m = COL_LINE_RE.match(line)
        if not m:
            continue
        col = m.group(1)
        typ = m.group(2).upper()
        acc[(table_name, col)] = typ


def extract_pk_columns(inner_pg: str) -> list[str]:
    """Imena kolona primarnog ključa (redosled kao u šemi)."""
    m = re.search(r"PRIMARY\s+KEY\s*\(\s*([^)]+)\)", inner_pg, re.I | re.S)
    if not m:
        return []
    return re.findall(r'"([^"]+)"', m.group(1))


def build_create_table_sql(
    table_name: str, inner: str, column_pg_types: dict[tuple[str, str], str]
) -> tuple[str, list[str]]:
    lines = inner.splitlines()
    out_lines: list[str] = []
    for line in lines:
        comp = convert_computed_datum_nabavke(line)
        if comp is not None:
            out_lines.append(comp + ",")
            continue
        out_lines.append(line)

    inner_joined = "\n".join(out_lines)
    inner_joined = convert_mssql_types(inner_joined)
    inner_joined = convert_bracket_idents(inner_joined)
    inner_joined = strip_sql_server_index_options(inner_joined)

    collect_column_pg_types(table_name, inner_joined, column_pg_types)
    pk_cols = extract_pk_columns(inner_joined)

    tbl = qident(table_name)
    sql = f"CREATE TABLE public.{tbl} (\n{inner_joined}\n);\n"
    return sql, pk_cols


def extract_default_and_for(batch_one_line: str) -> tuple[str, str, str, str] | None:
    """
    Vraća (table, col, expr_raw_wo_outer_parens) za ALTER ... DEFAULT ... FOR.
    Ili None.
    """
    m = re.search(
        r"ALTER\s+TABLE\s+\[dbo\]\.\[([^\]]+)\]\s+"
        r"ADD\s+(?:CONSTRAINT\s+\[[^\]]+\]\s+)?"
        r"DEFAULT\s+",
        batch_one_line,
        re.I,
    )
    if not m:
        return None
    table = m.group(1)
    i = m.end()
    if not batch_one_line[i:].strip().startswith("("):
        return None
    depth = 0
    j = i
    start_expr = j
    while j < len(batch_one_line):
        c = batch_one_line[j]
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                expr_full = batch_one_line[start_expr : j + 1]
                rest = batch_one_line[j + 1 :]
                mfor = re.match(
                    r"\s+FOR\s+\[([^\]]+)\]", rest, re.I
                )
                if not mfor:
                    return None
                col = mfor.group(1)
                inner = expr_full[1:-1] if expr_full.startswith("(") else expr_full
                return (table, col, inner, expr_full)
        j += 1
    return None


def convert_default_expression(expr: str) -> str:
    e = expr.strip()
    el = e.lower()
    # SQL Server cast na „datum bez vremena“
    if "convert" in el and "getdate" in el:
        if "datepart" in el and "year" in el:
            return "EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER"
        return "(CURRENT_DATE::timestamp)"
    if re.match(r"^getdate\s*\(\s*\)$", el):
        return "CURRENT_TIMESTAMP"
    # SQL Server: login korisnika → Postgres korisnik sesije
    if re.match(r"^suser_sname\s*\(\s*\)$", el):
        return "(SESSION_USER)::text"
    if re.match(r"^\(\s*\(\s*-?\d+\s*\)\s*\)$", e):
        inner = re.search(r"\(\s*\(([^)]+)\)\s*\)", e)
        return inner.group(1).strip() if inner else e
    if re.match(r"^\(\s*-?\d+\s*\)$", e):
        return re.search(r"\(([^)]+)\)", e).group(1).strip()
    if re.match(r"^\(\s*'[^']*'\s*\)$", e):
        return e.strip("()").strip()
    # ostavi kao što jeste ali konvertuj identifikatore u navodnicima kasnije
    e2 = convert_bracket_idents(e)
    e2 = re.sub(r"\bgetdate\s*\(\s*\)", "CURRENT_TIMESTAMP", e2, flags=re.I)
    e2 = re.sub(r"\bsuser_sname\s*\(\s*\)", "(SESSION_USER)::text", e2, flags=re.I)
    return e2


def _strip_numeric_parens(expr: str) -> str:
    s = expr.strip()
    while s.startswith("(") and s.endswith(")"):
        inner = s[1:-1].strip()
        if re.fullmatch(r"-?\d+", inner):
            return inner
        s = inner
    return s


def fix_boolean_default(
    alter_line: str, column_pg_types: dict[tuple[str, str], str]
) -> str:
    m = re.match(
        r'^ALTER TABLE public\.("([^"]+)")\s+ALTER COLUMN\s+("([^"]+)")\s+'
        r"SET DEFAULT\s+(.+);\s*$",
        alter_line.strip(),
    )
    if not m:
        return alter_line
    table, col, expr = m.group(2), m.group(4), m.group(5).strip()
    typ = column_pg_types.get((table, col))
    if typ != "BOOLEAN":
        return alter_line
    n = _strip_numeric_parens(expr)
    if n == "0":
        new_expr = "false"
    elif n == "1":
        new_expr = "true"
    else:
        return alter_line
    return (
        f"ALTER TABLE public.{qident(table)} "
        f"ALTER COLUMN {qident(col)} SET DEFAULT {new_expr};"
    )


def parse_default_alter(batch: str) -> str | None:
    """Jedan ALTER po batch-u ili None."""
    batch_one_line = batch_to_single_line_preserve_brackets(batch)
    ext = extract_default_and_for(batch_one_line)
    if not ext:
        return None
    table, col, expr_inner, _ = ext
    pg_expr = convert_default_expression(expr_inner)
    return (
        f"ALTER TABLE public.{qident(table)} "
        f"ALTER COLUMN {qident(col)} SET DEFAULT {pg_expr};"
    )


def parse_fk_alter(batch: str) -> tuple[str, str, str] | None:
    """
    Vraća (sql, parent_table, parent_col) za jedan FK ALTER, ili None.
    parent_* služe da se doda UNIQUE na referisanu kolonu ako nije PK (zahtev Postgresa).
    """
    text = batch_to_single_line_preserve_brackets(batch)
    if "FOREIGN KEY" not in text.upper() or "REFERENCES" not in text.upper():
        return None

    m = re.search(
        r"ALTER\s+TABLE\s+\[dbo\]\.\[([^\]]+)\]\s+WITH\s+(?:NOCHECK|CHECK)\s+ADD\s+"
        r"CONSTRAINT\s+\[([^\]]+)\]\s+FOREIGN\s+KEY\s*\(\s*\[([^\]]+)\]\s*\)\s+"
        r"REFERENCES\s+\[dbo\]\.\[([^\]]+)\]\s*\(\s*\[([^\]]+)\]\s*\)"
        r"(.*?)(?:\s+GO\s*$)?",
        text,
        re.I | re.S,
    )
    if not m:
        return None
    child_table, fk_name, child_col, parent_table, parent_col, rest = m.groups()
    rest_u = rest.upper()
    ouc = " ON UPDATE CASCADE" if "ON UPDATE CASCADE" in rest_u else ""
    odc = ""
    if "ON DELETE CASCADE" in rest_u:
        odc = " ON DELETE CASCADE"
    elif "ON DELETE SET NULL" in rest_u:
        odc = " ON DELETE SET NULL"

    sql = (
        f"ALTER TABLE public.{qident(child_table)} "
        f"ADD CONSTRAINT {qident(fk_name)} "
        f"FOREIGN KEY ({qident(child_col)}) "
        f"REFERENCES public.{qident(parent_table)} ({qident(parent_col)})"
        f"{ouc}{odc};"
    )
    return sql, parent_table, parent_col


def fk_needs_unique_on_parent(
    parent_table: str, parent_col: str, table_pks: dict[str, list[str]]
) -> bool:
    """Postgres zahteva PK ili UNIQUE na referisanim kolonama."""
    pk = table_pks.get(parent_table)
    if not pk:
        return False
    return not (len(pk) == 1 and pk[0] == parent_col)


def unique_constraint_for_fk_column(parent_table: str, parent_col: str) -> str:
    cname = f"UQ_{parent_table}_{parent_col}".replace(" ", "_")
    if len(cname) > 63:
        cname = cname[:63]
    return (
        f"ALTER TABLE public.{qident(parent_table)} "
        f"ADD CONSTRAINT {qident(cname)} UNIQUE ({qident(parent_col)});"
    )


def main() -> int:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else SRC
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else OUT

    if not src.is_file():
        print(f"Nema izvornog fajla: {src}", file=sys.stderr)
        return 1

    raw = src.read_text(encoding="utf-8", errors="replace")

    header = (
        "-- PostgreSQL šema generisana iz SQL Server dump-a\n"
        "-- Encoding: UTF-8\n\n"
        "SET client_encoding = 'UTF8';\n\n"
    )

    column_pg_types: dict[tuple[str, str], str] = {}
    blocks = extract_create_table_blocks(raw)
    table_pks: dict[str, list[str]] = {}
    table_sql: list[str] = []
    for t, inner in blocks:
        sql, pk = build_create_table_sql(t, inner, column_pg_types)
        table_sql.append(sql)
        table_pks[t] = pk

    defaults_sql: list[str] = []
    fks_sql: list[str] = []
    need_unique: set[tuple[str, str]] = set()

    for batch in split_go_batches(raw):
        if "ALTER TABLE" not in batch.upper():
            continue
        if "CHECK CONSTRAINT" in batch.upper() and "FOREIGN KEY" not in batch.upper():
            continue
        d = parse_default_alter(batch)
        if d:
            defaults_sql.append(fix_boolean_default(d, column_pg_types))
            continue
        fk = parse_fk_alter(batch)
        if fk:
            stmt, ptab, pcol = fk
            if fk_needs_unique_on_parent(ptab, pcol, table_pks):
                need_unique.add((ptab, pcol))
            fks_sql.append(stmt)

    unique_sql = [unique_constraint_for_fk_column(t, c) for t, c in sorted(need_unique)]

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        header
        + "\n-- === Tabele ===\n\n"
        + "\n".join(table_sql)
        + "\n-- === Podrazumevane vrednosti ===\n\n"
        + "\n".join(defaults_sql)
        + "\n\n-- === UNIQUE (kolone koje FK referišu a nisu same PK; Postgres zahtev) ===\n\n"
        + "\n".join(unique_sql)
        + "\n\n-- === Strani ključevi ===\n\n"
        + "\n".join(fks_sql)
        + "\n",
        encoding="utf-8",
    )

    print(
        f"Upisano: {out}\n"
        f"  tabele: {len(table_sql)}\n"
        f"  default alter: {len(defaults_sql)}\n"
        f"  unique (za FK): {len(unique_sql)}\n"
        f"  FK alter: {len(fks_sql)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
