-- PostgreSQL šema generisana iz SQL Server dump-a
-- Encoding: UTF-8

SET client_encoding = 'UTF8';


-- === Tabele ===

CREATE TABLE public."tRN" (

	"IDRN" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDPredmet" INTEGER NOT NULL,
	"IdentBroj" VARCHAR(50) NOT NULL,
	"Varijanta" INTEGER NOT NULL,
	"BBIDKomitent" INTEGER NOT NULL,
	"BBNazivPredmeta" VARCHAR(250) NULL,
	"BBDatumOtvaranja" TIMESTAMP NOT NULL,
	"DatumUnosa" TIMESTAMP NOT NULL,
	"Komada" INTEGER NOT NULL,
	"BrojCrteza" VARCHAR(100) NOT NULL,
	"Proizvod" VARCHAR(150) NULL,
	"TezinaNeobrDela" DOUBLE PRECISION NULL,
	"NazivDela" VARCHAR(250) NOT NULL,
	"IdentMaterijala" INTEGER NULL,
	"Materijal" VARCHAR(250) NOT NULL,
	"DimenzijaMaterijala" VARCHAR(150) NOT NULL,
	"JM" VARCHAR(50) NOT NULL,
	"TezinaObrDela" DOUBLE PRECISION NULL,
	"Napomena" TEXT NULL,
	"StatusRN" BOOLEAN NULL,
	"RokIzrade" TIMESTAMP NULL,
	"DIVUnosaRN" TIMESTAMP NOT NULL,
	"DIVIspravkeRN" TIMESTAMP NOT NULL,
	"SifraRadnika" INTEGER NOT NULL,
	"Zakljucano" BOOLEAN NULL,
	"Potpis" VARCHAR(50) NULL,
	"PrnTimer" INTEGER NULL,
	"VezaSaBrojemCrteza" VARCHAR(100) NULL,
	"IDVrstaKvaliteta" INTEGER NOT NULL,
	"Revizija" VARCHAR(3) NOT NULL,
	"IDPrimopredaje" INTEGER NOT NULL,
	"IDCrtez" INTEGER NOT NULL,
	"IDStatusPrimopredaje" INTEGER NOT NULL,
	"SifraRadnikaPrimopredaje" INTEGER NOT NULL,
 CONSTRAINT "aaaaatRN_PK" PRIMARY KEY  
(
	"IDRN"
)
);

CREATE TABLE public."Predmeti" (

	"IDPredmet" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"BrojPredmeta" VARCHAR(20) NOT NULL,
	"Opis" VARCHAR(50) NULL,
	"DatumOtvaranja" TIMESTAMP NULL,
	"IDProdavac" INTEGER NOT NULL,
	"IDKomitent" INTEGER NOT NULL,
	"NextAction" VARCHAR(50) NULL,
	"DatumZakljucenja" TIMESTAMP NULL,
	"Memo" TEXT NULL,
	"Status" VARCHAR(20) NULL,
	"NasaRef" VARCHAR(20) NULL,
	"NasKontakt1" VARCHAR(50) NULL,
	"NasKontakt2" VARCHAR(50) NULL,
	"NasTel1" VARCHAR(20) NULL,
	"NasTel2" VARCHAR(20) NULL,
	"VasaRef" VARCHAR(20) NULL,
	"VasKontakt1" VARCHAR(50) NULL,
	"VasKontakt2" VARCHAR(50) NULL,
	"VasTel1" VARCHAR(20) NULL,
	"VasTel2" VARCHAR(20) NULL,
	"NabavnaVrednost" NUMERIC(19,4) NULL,
	"Carina" NUMERIC(19,4) NULL,
	"Spedicija" NUMERIC(19,4) NULL,
	"Prevoz" NUMERIC(19,4) NULL,
	"Ostalo" NUMERIC(19,4) NULL,
	"InoDobavljac" INTEGER NULL,
	"RJ" VARCHAR(4) NULL,
	"devvaluta" VARCHAR(3) NULL,
	"kurs" NUMERIC(19,4) NULL,
	"IDVrstaPosla" INTEGER NULL,
	"NazivPredmeta" VARCHAR(250) NULL,
	"RokZavrsetka" TIMESTAMP NULL,
	"Potpis" VARCHAR(50) NULL,
	"DatumIVreme" TIMESTAMP NULL,
	"BrojUgovora" VARCHAR(100) NULL,
	"DatumUgovora" TIMESTAMP NULL,
	"BrojNarudzbenice" VARCHAR(100) NULL,
	"DatumNarudzbenice" TIMESTAMP NULL,
 CONSTRAINT "PK_Predmeti" PRIMARY KEY  
(
	"IDPredmet"
)
);

CREATE TABLE public."Komitenti" (

	"Sifra" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Naziv" VARCHAR(50) NOT NULL,
	"Poslovnica" VARCHAR(50) NULL,
	"Mesto" VARCHAR(30) NULL,
	"Adresa" VARCHAR(50) NULL,
	"Postanski broj" VARCHAR(20) NULL,
	"Ziro racun_1" VARCHAR(30) NULL,
	"Ziro racun_2" VARCHAR(30) NULL,
	"Ziro racun_3" VARCHAR(30) NULL,
	"Telefon" VARCHAR(20) NULL,
	"Fax" VARCHAR(20) NULL,
	"Kontakt" VARCHAR(50) NULL,
	"Napomena" TEXT NULL,
	"Drzava" VARCHAR(30) NULL,
	"Region" INTEGER NULL,
	"Vrsta sifre" VARCHAR(10) NULL,
	"Email" VARCHAR(50) NULL,
	"Mobilni" VARCHAR(20) NULL,
	"Datum rodjenja" TIMESTAMP NULL,
	"Web adresa" VARCHAR(50) NULL,
	"Sifra prodavca" INTEGER NULL,
	"RabatKomitenta" DOUBLE PRECISION NULL,
	"ZastKodKupca" VARCHAR(50) NULL,
	"PIB" VARCHAR(20) NOT NULL,
	"PDVStatus" INTEGER NULL,
	"MSifra" VARCHAR(10) NULL,
	"Odlozeno" SMALLINT NULL,
	"IDRuta" INTEGER NULL,
	"IDVozac" INTEGER NULL,
	"IDUplatniRacun" INTEGER NULL,
	"FakturisanjePoMestimaIsporuke" BOOLEAN NULL,
	"Cenovnik" VARCHAR(5) NULL,
	"PrviUnos" TIMESTAMP NULL,
	"PoslednjaIzmena" TIMESTAMP NULL,
	"PrviUnosUser" VARCHAR(20) NULL,
	"PoslednjaIzmenaUser" VARCHAR(20) NULL,
	"ProcenatProvizije" DOUBLE PRECISION NULL,
	"FiktRabatKomitenta" DOUBLE PRECISION NULL,
	"KomitentiNacinPlacanja" VARCHAR(50) NULL,
	"PotpisKom" VARCHAR(50) NULL,
	"SkraceniNaziv" VARCHAR(30) NULL,
	"DatumIVremeKom" TIMESTAMP NULL,
	"ProveraDuga" BOOLEAN NULL,
	"KreditLimit" NUMERIC(19,4) NULL,
	"NeProveravajPIB" BOOLEAN NULL,
	"IDPantheon" VARCHAR(30) NULL,
	"NewsLetter" BOOLEAN NULL,
	"PostaNaDruguAdresu" BOOLEAN NULL,
	"GLN" VARCHAR(30) NULL,
	"KLRucProc" NUMERIC(19,4) NULL,
	"NapomenaZaSalda" TEXT NULL,
	"NePrikazatiUPregledu" BOOLEAN NULL,
	"JBKJS" VARCHAR(10) NULL,
	"MaticniBroj" VARCHAR(20) NULL,
	"ER_XMLSaPopustomPoArtiklu" BOOLEAN NULL,
	"CRF" BOOLEAN NULL,
 CONSTRAINT "PK_Komitenti" PRIMARY KEY  
(
	"Sifra"
)
);

CREATE TABLE public."tTehPostupak" (

	"IDPostupka" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"SifraRadnika" INTEGER NOT NULL,
	"IDPredmet" INTEGER NOT NULL,
	"IdentBroj" VARCHAR(50) NOT NULL,
	"Varijanta" INTEGER NOT NULL,
	"PrnTimer" INTEGER NULL,
	"DatumIVremeUnosa" TIMESTAMP NOT NULL,
	"Operacija" INTEGER NOT NULL,
	"RJgrupaRC" VARCHAR(5) NOT NULL,
	"Toznaka" VARCHAR(50) NOT NULL,
	"Komada" INTEGER NOT NULL,
	"Potpis" VARCHAR(50) NULL,
	"SimbolRadnik" BOOLEAN NULL,
	"SimbolPostupak" BOOLEAN NULL,
	"SimbolOperacija" BOOLEAN NULL,
	"DatumIVremeZavrsetka" TIMESTAMP NULL,
	"ZavrsenPostupak" BOOLEAN NULL,
	"Napomena" TEXT NULL,
	"IDRN" INTEGER NOT NULL,
	"IDVrstaKvaliteta" INTEGER NOT NULL,
	"DoradaOperacije" INTEGER NULL,
 CONSTRAINT "PK_tTehPostupak" PRIMARY KEY  
(
	"IDPostupka"
)
);

CREATE TABLE public."tStavkeRN" (

	"IDStavkeRN" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDRN" INTEGER NOT NULL,
	"Operacija" INTEGER NOT NULL,
	"RJgrupaRC" VARCHAR(5) NOT NULL,
	"OpisRada" TEXT NOT NULL,
	"AlatPribor" VARCHAR(50) NULL,
	"Tpz" DOUBLE PRECISION NULL,
	"Tk" DOUBLE PRECISION NULL,
	"TezinaTO" DOUBLE PRECISION NULL,
	"SifraRadnika" INTEGER NOT NULL,
	"DIVUnosa" TIMESTAMP NOT NULL,
	"DIVIspravke" TIMESTAMP NOT NULL,
	"Prioritet" INTEGER NOT NULL,
 CONSTRAINT "PK_tStavkeRN" PRIMARY KEY  
(
	"IDStavkeRN"
)
);

CREATE TABLE public."PDMCrtezi" (

	"IDCrtez" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"pdmWeID" VARCHAR(20) NOT NULL,
	"TransactionDate" TIMESTAMP NULL,
	"DesignDate" TIMESTAMP NULL,
	"DesignBy" VARCHAR(50) NULL,
	"ApprovedDate" TIMESTAMP NULL,
	"ApprovedBy" VARCHAR(50) NULL,
	"BrojCrteza" VARCHAR(20) NOT NULL,
	"Revizija" VARCHAR(3) NOT NULL,
	"Kolicina" INTEGER NOT NULL,
	"KataloskiBroj" VARCHAR(50) NOT NULL,
	"Naziv" VARCHAR(255) NOT NULL,
	"Materijal" VARCHAR(255) NULL,
	"RN" VARCHAR(20) NULL,
	"Dimenzije" VARCHAR(255) NULL,
	"Oznaka" VARCHAR(20) NOT NULL,
	"Tezina" DOUBLE PRECISION NULL,
	"Naziv fajla" VARCHAR(500) NULL,
	"PDMStatusCrteza" VARCHAR(20) NOT NULL,
	"Comment" VARCHAR(255) NULL,
	"WhereUsed" VARCHAR(255) NULL,
	"Naziv_projekta" VARCHAR(255) NULL,
	"DIVUnosa" TIMESTAMP NULL,
	"Potpis" VARCHAR(50) NULL,
	"IDStatusCrteza" INTEGER NOT NULL,
	"Nabavka" BOOLEAN NOT NULL,
 CONSTRAINT "PK_Crtez" PRIMARY KEY  
(
	"IDCrtez"
),
 CONSTRAINT "UQ_Crtez_BrojRev" UNIQUE  
(
	"BrojCrteza",
	"Revizija"
)
);

CREATE TABLE public."NacrtPrimopredaje" (

	"IDNacrtPrim" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDProjektant" INTEGER NOT NULL,
	"DatumNacrta" TIMESTAMP NOT NULL,
	"IDPredmet" INTEGER NOT NULL,
	"BrojKomada" INTEGER NOT NULL,
	"IDStatusNacrtaPrimopredaje" INTEGER NOT NULL,
	"Napomena" VARCHAR(250) NULL,
	"Potpis" VARCHAR(30) NULL,
	"PrviUnos" TIMESTAMP NULL,
	"PoslednjaIzmena" TIMESTAMP NULL,
	"BrojNacrta" VARCHAR(30) NOT NULL,
	"Zakljucano" BOOLEAN NULL,
	"TipNacrta" SMALLINT NOT NULL,
	"IDGlavniCrtez" INTEGER NULL,
PRIMARY KEY  
(
	"IDNacrtPrim"
)
);

CREATE TABLE public."NacrtPrimopredajeStavke" (

	"IDNacrtStavka" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDNacrtPrim" INTEGER NOT NULL,
	"IDCrtez" INTEGER NOT NULL,
	"Napomena" VARCHAR(250) NULL,
	"Potpis" VARCHAR(30) NULL,
	"PrviUnos" TIMESTAMP NULL,
	"PoslednjaIzmena" TIMESTAMP NULL,
	"KolicinaZaIzradu" INTEGER NOT NULL,
	"IDGlavniCrtez" INTEGER NULL,
	"IsGlavni" BOOLEAN NOT NULL,
	"PredProveraDuplikat" BOOLEAN NOT NULL,
	"PredProveraIDNacrtPrim" INTEGER NULL,
	"PredProveraIDRN" INTEGER NULL,
	"IskljuciPrimopredaju" BOOLEAN NOT NULL,
	"OdlukaAkcija" SMALLINT NOT NULL,
	"DIVOdluke" TIMESTAMP(0) NULL,
	"KolicinaDefinisanaUCrtezu" INTEGER NULL,
PRIMARY KEY  
(
	"IDNacrtStavka"
)
);

CREATE TABLE public."tSaglasanRN" (

	"IDSaglasan" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDRN" INTEGER NOT NULL,
	"Saglasan" BOOLEAN NULL,
	"DatumUnosa" TIMESTAMP NOT NULL,
	"DIVUnos" TIMESTAMP NOT NULL,
	"SifraRadnikaUnos" INTEGER NOT NULL,
	"PotpisUnos" VARCHAR(50) NULL,
	"DIVIspravke" TIMESTAMP NOT NULL,
	"SifraRadnikaIspravka" INTEGER NOT NULL,
	"PotpisIspravka" VARCHAR(50) NULL,
 CONSTRAINT "PK_tSaglasanRN" PRIMARY KEY  
(
	"IDSaglasan"
)
);

CREATE TABLE public."tLansiranRN" (

	"IDLansiran" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDRN" INTEGER NOT NULL,
	"Lansiran" BOOLEAN NULL,
	"DatumUnosa" TIMESTAMP NOT NULL,
	"DIVUnos" TIMESTAMP NOT NULL,
	"SifraRadnikaUnos" INTEGER NOT NULL,
	"PotpisUnos" VARCHAR(50) NULL,
	"DIVIspravke" TIMESTAMP NOT NULL,
	"SifraRadnikaIspravka" INTEGER NOT NULL,
	"PotpisIspravka" VARCHAR(50) NULL,
 CONSTRAINT "PK_tLansiranRN" PRIMARY KEY  
(
	"IDLansiran"
)
);

CREATE TABLE public."KomponentePDMCrteza" (

	"IDKomponenteCrteza" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ZaIDCrtez" INTEGER NOT NULL,
	"TrebaIDCrtez" INTEGER NOT NULL,
	"PotrebnoKomada" INTEGER NOT NULL,
 CONSTRAINT "PK_KomponentePDMCrteza" PRIMARY KEY  
(
	"IDKomponenteCrteza"
)
);

CREATE TABLE public."PDM_PDFCrtezi" (

	"BrojCrteza" VARCHAR(100) NOT NULL,
	"Revizija" VARCHAR(10) NOT NULL,
	"NazivFajla" VARCHAR(255) NULL,
	"DatumUnosa" TIMESTAMP NOT NULL,
	"VelicinaKB" INTEGER NULL,
	"KorisnikUnosa" VARCHAR(50) NULL,
	"PDFBinary" BYTEA NULL,
 CONSTRAINT "PK_PDM_PDFCrtezi" PRIMARY KEY  
(
	"BrojCrteza",
	"Revizija"
)
);

CREATE TABLE public."tRadnici" (

	"SifraRadnika" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Radnik" VARCHAR(50) NOT NULL,
	"ProcenatZaObracun" DOUBLE PRECISION NULL,
	"ImeIPrezime" VARCHAR(50) NULL,
	"BrLkRadnika" VARCHAR(20) NULL,
	"Password" VARCHAR(20) NULL,
	"Aktivan" BOOLEAN NULL,
	"IDRadneJedinice" VARCHAR(5) NOT NULL,
	"IDKartice" VARCHAR(50) NOT NULL,
	"LogAcc" VARCHAR(50) NULL,
	"IDVrsteRadnika" INTEGER NOT NULL,
	"PotpisSlika" VARCHAR(150) NULL,
	"DefiniseSaglasan" BOOLEAN NULL,
	"DefiniseLansiran" BOOLEAN NULL,
	"MultiNalog" BOOLEAN NULL,
	"PasswordRadnika" VARCHAR(50) NOT NULL,
 CONSTRAINT "aaaaatRadnici_PK" PRIMARY KEY  
(
	"SifraRadnika"
)
);

CREATE TABLE public."StatusiPrimopredaje" (

	"IDStatusPrimopredaje" INTEGER NOT NULL,
	"NazivStatusa" VARCHAR(50) NOT NULL,
 CONSTRAINT "PK_StatusiPrimopredaje" PRIMARY KEY  
(
	"IDStatusPrimopredaje"
),
UNIQUE  
(
	"NazivStatusa"
)
);

CREATE TABLE public."tRNKomponente" (

	"IDKomponente" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDRN" INTEGER NOT NULL,
	"IDRNPodkomponenta" INTEGER NOT NULL,
	"BrojKomada" INTEGER NOT NULL,
	"Napomena" VARCHAR(255) NULL,
PRIMARY KEY  
(
	"IDKomponente"
),
 CONSTRAINT "UQ_tRNKomponente_IDRN_IDPodkomponente" UNIQUE  
(
	"IDRN",
	"IDRNPodkomponenta"
)
);

CREATE TABLE public."PDM_Planiranje" (

	"IDPlan" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDPredmet" INTEGER NOT NULL,
	"IDCrtezSklopa" INTEGER NULL,
	"KolicinaZaIzradu" NUMERIC(18,4) NOT NULL,
	"StatusPlaniranja" INTEGER NOT NULL,
	"DatumPlaniranja" TIMESTAMP NOT NULL,
	"SifraRadnikaPlaniranja" INTEGER NOT NULL,
	"Napomena" VARCHAR(255) NULL,
	"Potpis" VARCHAR(30) NULL,
	"PrviUnos" TIMESTAMP NULL,
	"PoslednjaIzmena" TIMESTAMP NULL,
	"Zakljucano" BOOLEAN NULL,
	"BrojPlana" VARCHAR(30) NULL,
	"BrojCrtezaPlana" VARCHAR(20) NULL,
	"RevizijaPlana" VARCHAR(3) NULL,
 CONSTRAINT "PK_PDM_Planiranje" PRIMARY KEY  
(
	"IDPlan"
)
);

CREATE TABLE public."PDM_PlaniranjeStavke" (

	"IDPlanStavka" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDPlan" INTEGER NOT NULL,
	"IDCrtezNabavke" INTEGER NOT NULL,
	"SifraArtikla" INTEGER NULL,
	"KolicinaPoSklopu" NUMERIC(18,4) NOT NULL,
	"PotrebnoUkupno" NUMERIC(18,4) NULL,
	"PredProveraIDPlan" INTEGER NULL,
	"OdlukaAkcija" SMALLINT NOT NULL,
	"RucnaKolicina" NUMERIC(18,4) NULL,
	"Rezervisano" NUMERIC(18,4) NOT NULL,
	"ZaNabavku" NUMERIC(18,4) NOT NULL,
	"Zalihe" NUMERIC(18,4) NULL,
	"NazivArtiklaStavke" VARCHAR(150) NULL,
	"KataloskiBrojStavke" VARCHAR(20) NULL,
	"JMStavke" VARCHAR(5) NULL,
	"JeRucnaStavka" BOOLEAN NOT NULL,
	"IskljuciNabavku" BOOLEAN NOT NULL,
 CONSTRAINT "PK_PDM_PlaniranjeStavke" PRIMARY KEY  
(
	"IDPlanStavka"
)
);

CREATE TABLE public."MRP_Potrebe" (

	"IDPotreba" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDPredmet" INTEGER NOT NULL,
	"IDCrtezRoot" INTEGER NULL,
	"SifraRadnika" INTEGER NULL,
	"Izvor" SMALLINT NOT NULL,
	"TipEksplozije" SMALLINT NULL,
	"Status" SMALLINT NOT NULL,
	"DatumPotrebe" DATE NOT NULL,
	"Napomena" VARCHAR(500) NULL,
	"DIVUnosa" TIMESTAMP NOT NULL,
	"DIVUnosaKorisnik" VARCHAR(20) NULL,
	"DIVIzmena" TIMESTAMP NULL,
	"DIVIzmenaKorisnik" VARCHAR(20) NULL,
	"PlaniranaKolicina" NUMERIC(19,6) NOT NULL,
	"IDPlan" INTEGER NULL,
 CONSTRAINT "PK_MRP_Potrebe" PRIMARY KEY  
(
	"IDPotreba"
)
);

CREATE TABLE public."MRP_PotrebeStavke" (

	"IDPotrebaStavka" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDPotreba" INTEGER NOT NULL,
	"IDCrtezIzvora" INTEGER NULL,
	"IDCrtezNabavke" INTEGER NULL,
	"SifraArtikla" INTEGER NULL,
	"KataloskiBrojStavka" VARCHAR(100) NOT NULL,
	"NazivArtiklaStavka" VARCHAR(200) NOT NULL,
	"JedinicaMereStavka" VARCHAR(10) NOT NULL,
	"IzvorStavke" SMALLINT NOT NULL,
	"KolicinaPotrebna" NUMERIC(19,6) NOT NULL,
	"DatumPotrebe" DATE NOT NULL,
	"VremeIsporukeDana" INTEGER NULL,
	"DatumNabavke" DATE GENERATED ALWAYS AS (("DatumPotrebe" - COALESCE("VremeIsporukeDana", 0))) STORED,
	"Napomena" VARCHAR(500) NULL,
	"DIVUnosa" TIMESTAMP NOT NULL,
	"DIVUnosaKorisnik" VARCHAR(20) NULL,
	"DIVIzmena" TIMESTAMP NULL,
	"DIVIzmenaKorisnik" VARCHAR(20) NULL,
	"DobavljacID" INTEGER NULL,
	"StatusStavke" SMALLINT NOT NULL,
	"KolicinaRezervisano" NUMERIC(19,6) NOT NULL,
	"KolicinaZaNabavku" NUMERIC(19,6) NOT NULL,
 CONSTRAINT "PK_MRP_PotrebeStavke" PRIMARY KEY  
(
	"IDPotrebaStavka"
)
);

CREATE TABLE public."tOperacije" (

	"RJgrupaRC" VARCHAR(5) NOT NULL,
	"NazivGrupeRC" VARCHAR(50) NOT NULL,
	"Napomena" VARCHAR(255) NULL,
	"IDRadneJedinice" VARCHAR(5) NOT NULL,
	"BezPostupka" BOOLEAN NULL,
	"ZnacajneOperacijeZaZavrsen" BOOLEAN NULL,
	"KoristiPrioritet" BOOLEAN NOT NULL,
	"IDOperacije" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"PreskocivaOperacija" BOOLEAN NOT NULL,
 CONSTRAINT "PK_tOperacije" PRIMARY KEY  
(
	"IDOperacije"
)
);

CREATE TABLE public."RobneStavkeMirror" (

	"IDStavke" INTEGER NOT NULL,
	"IDDok" INTEGER NOT NULL,
	"SifraArtikla" INTEGER NOT NULL,
	"KataloskiBroj" VARCHAR(100) NULL,
	"IDMagacin" INTEGER NOT NULL,
	"KolicinaUlaz" NUMERIC(18,4) NOT NULL,
	"KolicinaIzlaz" NUMERIC(18,4) NOT NULL,
	"PoslednjaIzmena" TIMESTAMP NOT NULL,
PRIMARY KEY  
(
	"IDStavke"
)
);

CREATE TABLE public."tVrsteRadnika" (

	"IDVrsteRadnika" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"VrstaRadnika" VARCHAR(50) NOT NULL,
	"DodatnaOvlascenja" BOOLEAN NOT NULL,
 CONSTRAINT "PK_tVrsteRadnika" PRIMARY KEY  
(
	"IDVrsteRadnika"
)
);

CREATE TABLE public."tTehPostupakDokumentacija" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDPostupka" INTEGER NOT NULL,
	"LinkFajla" VARCHAR(250) NOT NULL,
	"ImeFajla" VARCHAR(50) NOT NULL,
 CONSTRAINT "PK_tTehPostupakDokumentacija" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."StatusiCrteza" (

	"IDStatusCrteza" INTEGER NOT NULL,
	"NazivStatusa" VARCHAR(50) NOT NULL,
PRIMARY KEY  
(
	"IDStatusCrteza"
)
);

CREATE TABLE public."tVrsteKvalitetaDelova" (

	"IDVrstaKvaliteta" INTEGER NOT NULL,
	"VrstaKvaliteta" VARCHAR(50) NOT NULL,
 CONSTRAINT "PK_IDVrstaKvaliteta" PRIMARY KEY  
(
	"IDVrstaKvaliteta"
)
);

CREATE TABLE public."tPozicije" (

	"IDPozicije" INTEGER NOT NULL,
	"Pozicija" VARCHAR(20) NOT NULL,
	"Opis" VARCHAR(250) NULL,
 CONSTRAINT "PK_tPozicije" PRIMARY KEY  
(
	"IDPozicije"
)
);

CREATE TABLE public."tLokacijeDelova" (

	"IDLokacije" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDRN" INTEGER NOT NULL,
	"IDPredmet" INTEGER NOT NULL,
	"IDVrstaKvaliteta" INTEGER NOT NULL,
	"IDPozicija" INTEGER NOT NULL,
	"SifraRadnika" INTEGER NOT NULL,
	"Datum" TIMESTAMP NOT NULL,
	"Kolicina" INTEGER NOT NULL,
	"DatumIVremeUnosa" TIMESTAMP NULL,
 CONSTRAINT "PK_tLokacijeDelova" PRIMARY KEY  
(
	"IDLokacije"
)
);

CREATE TABLE public."T_Planer" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDFirma" INTEGER NOT NULL,
	"KadaDatum" TIMESTAMP NOT NULL,
	"KadaVreme" TIMESTAMP NOT NULL,
	"OdKoga" VARCHAR(50) NOT NULL,
	"ZaKoga" VARCHAR(50) NOT NULL,
	"Subject" VARCHAR(255) NOT NULL,
	"Prioritet" INTEGER NOT NULL,
	"Poruka" TEXT NULL,
	"RepeatCode" VARCHAR(10) NOT NULL,
	"CheckUradjeno" BOOLEAN NOT NULL,
	"KadaJeUradjeno" TIMESTAMP NULL,
	"KoJeUradio" VARCHAR(50) NULL,
	"IDProgToExecute" VARCHAR(255) NULL,
	"AutoExec" BOOLEAN NOT NULL,
	"DIVPrviUnos" TIMESTAMP NOT NULL,
	"DIVPoslednjaIzmena" TIMESTAMP NULL,
 CONSTRAINT "PK_T_Planer" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."T_PlanerGrupeUsera" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"NazivGrupe" VARCHAR(50) NOT NULL,
	"UserName" VARCHAR(50) NOT NULL,
PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."_Dnevnik" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Opis" TEXT NOT NULL,
	"DIV" TIMESTAMP NOT NULL,
 CONSTRAINT "PK__Dnevnik" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."_RegAccess" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"HDSn" VARCHAR(100) NULL,
	"WinUser" VARCHAR(100) NULL,
	"ComputerName" VARCHAR(100) NULL,
	"IPAdress" VARCHAR(100) NULL,
	"Program_Name" VARCHAR(255) NULL,
	"CNNString" VARCHAR(255) NULL,
	"Login_Time" TIMESTAMP NULL,
 CONSTRAINT "PK_RegAccess" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."_RegApps" (

	"DBName" VARCHAR(100) NULL,
	"AppName" VARCHAR(100) NOT NULL,
	"Disabled" BOOLEAN NOT NULL,
	"AplFile" VARCHAR(250) NOT NULL,
	"MDWFile" VARCHAR(250) NULL,
	"ClientDir" VARCHAR(250) NULL,
	"DownloadDir" VARCHAR(1000) NULL,
	"PrviUnos" TIMESTAMP NULL,
	"PoslednjaIzmena" TIMESTAMP NULL,
 CONSTRAINT "PK__RegApp" PRIMARY KEY  
(
	"AppName"
)
);

CREATE TABLE public."_RegAppsFiles" (

	"DBName" VARCHAR(100) NULL,
	"AppName" VARCHAR(100) NOT NULL,
	"AppFileName" VARCHAR(255) NOT NULL,
	"ClientDir" VARCHAR(255) NOT NULL,
	"Install" BOOLEAN NOT NULL,
	"Update" BOOLEAN NOT NULL,
	"PrviUnos" TIMESTAMP NULL,
	"PoslednjaIzmena" TIMESTAMP NULL,
 CONSTRAINT "PK__RegAppFile" PRIMARY KEY  
(
	"AppName",
	"AppFileName"
)
);

CREATE TABLE public."_RegUsers" (

	"DBName" VARCHAR(100) NULL,
	"RegUserID" INTEGER NOT NULL,
	"Disabled" BOOLEAN NOT NULL,
	"HDSn" VARCHAR(100) NOT NULL,
	"WinUser" VARCHAR(100) NOT NULL,
	"ComputerName" VARCHAR(100) NOT NULL,
	"IPAdress" VARCHAR(100) NULL,
	"Name" VARCHAR(100) NULL,
	"email" VARCHAR(100) NULL,
	"Telefon" VARCHAR(100) NULL,
	"Opis" VARCHAR(200) NULL,
	"VaziOdDatuma" DATE NULL,
	"VaziDoDatuma" DATE NULL,
	"PrviUnos" TIMESTAMP NULL,
	"PoslednjaIzmena" TIMESTAMP NULL,
 CONSTRAINT "PK__Users" PRIMARY KEY  
(
	"RegUserID"
)
);

CREATE TABLE public."_RegUsersApps" (

	"DBName" VARCHAR(100) NULL,
	"RegUserID" INTEGER NOT NULL,
	"AppName" VARCHAR(100) NOT NULL,
	"Disabled" BOOLEAN NOT NULL,
	"BBUserName" VARCHAR(50) NULL,
	"BBPassword" VARCHAR(50) NULL,
	"BBMacroName" VARCHAR(100) NULL,
	"EXCL" BOOLEAN NOT NULL,
	"RUNTIME" BOOLEAN NOT NULL,
	"BBExtraStartUp" VARCHAR(100) NULL,
	"BBCMD" VARCHAR(100) NULL,
	"PrviUnos" TIMESTAMP NULL,
	"PoslednjaIzmena" TIMESTAMP NULL,
 CONSTRAINT "PK__RegUsersApps" PRIMARY KEY  
(
	"RegUserID",
	"AppName"
)
);

CREATE TABLE public."_Rev" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"APP" VARCHAR(20) NOT NULL,
	"Ver" VARCHAR(50) NOT NULL,
	"VerDatum" TIMESTAMP NOT NULL,
	"Tema" VARCHAR(100) NOT NULL,
	"Opis" TEXT NULL,
	"Uradjeno" BOOLEAN NOT NULL,
	"Firma" VARCHAR(30) NULL,
	"DIVUnos" TIMESTAMP NOT NULL,
	"SubRev" INTEGER NOT NULL,
 CONSTRAINT "aaaaa_AppRev_PK" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."BBDefUser" (

	"UserName" VARCHAR(20) NOT NULL,
	"DefaultGodina" INTEGER NULL,
	"DefaultOJ" INTEGER NULL,
	"DefaultOD" INTEGER NULL,
	"UnlockGodina" BOOLEAN NULL,
	"UnlockOJ" BOOLEAN NULL,
	"UnlockOD" BOOLEAN NULL,
	"Level" SMALLINT NULL,
	"MaxLevel" SMALLINT NULL,
 CONSTRAINT "aaaaaBBDefUser_PK" PRIMARY KEY  
(
	"UserName"
)
);

CREATE TABLE public."BBOdeljenja" (

	"OD" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"OznakaOD" VARCHAR(10) NOT NULL,
	"OpisOD" VARCHAR(50) NOT NULL,
 CONSTRAINT "aaaaaBBOdeljenja_PK" PRIMARY KEY  
(
	"OD"
)
);

CREATE TABLE public."BBOrgJedinice" (

	"OJ" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"OznakaOJ" VARCHAR(10) NOT NULL,
	"OpisOJ" VARCHAR(50) NOT NULL,
 CONSTRAINT "aaaaaBBOrgJedinice_PK" PRIMARY KEY  
(
	"OJ"
)
);

CREATE TABLE public."BBPravaPristupa" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ImeUsera" VARCHAR(20) NOT NULL,
	"ImeForme" VARCHAR(50) NOT NULL,
	"ImeKontrole" VARCHAR(50) NOT NULL,
	"Visible" BOOLEAN NOT NULL,
	"Locked" BOOLEAN NOT NULL,
	"Enabled" BOOLEAN NOT NULL,
	"Vrednost" VARCHAR(250) NULL,
	"RecordSource" TEXT NULL,
	"Filter" VARCHAR(250) NULL,
 CONSTRAINT "aaaaaBBPravaPristupa_PK" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."Cenovnik" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Sifra artikla" INTEGER NOT NULL,
	"Vrsta dokumenta" VARCHAR(5) NOT NULL,
	"Cena" DOUBLE PRECISION NULL,
	"Tarifa" VARCHAR(5) NOT NULL,
	"CenaBezPDV" NUMERIC(19,4) NULL,
	"Taksa" DOUBLE PRECISION NULL,
	"Prn" BOOLEAN NULL,
	"CenaSaPDV" NUMERIC(19,4) NULL,
	"CheckCenaSaPDV" BOOLEAN NULL,
	"ZakCen" BOOLEAN NULL,
 CONSTRAINT "PK_Cenovnik" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."CFG_Global" (

	"IDFirma" INTEGER NOT NULL,
	"Parametar" VARCHAR(120) NOT NULL,
	"Vrednost" TEXT NULL,
	"Tip" VARCHAR(20) NULL,
	"Opis" VARCHAR(100) NULL,
 CONSTRAINT "CFG_Global_PK" PRIMARY KEY  
(
	"IDFirma",
	"Parametar"
)
);

CREATE TABLE public."CFG_Sys" (

	"Parametar" VARCHAR(120) NOT NULL,
	"Vrednost" VARCHAR(50) NULL,
	"Tip" VARCHAR(20) NULL,
	"Opis" VARCHAR(255) NULL,
	"DIVUnos" TIMESTAMP NULL,
 CONSTRAINT "PK_CFG_Sys" PRIMARY KEY  
(
	"Parametar"
)
);

CREATE TABLE public."Info" (

	"ID" INTEGER NOT NULL,
	"DatumIVremeSlanja" TIMESTAMP NULL,
	"KoJePoslao" VARCHAR(250) NULL,
	"Prijem" BOOLEAN NULL,
	"DatumIVremePrijema" TIMESTAMP NULL,
	"KoJePrimio" VARCHAR(250) NULL,
 CONSTRAINT "aaaaaInfo_PK" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."Magacini" (

	"IDFirma" INTEGER NULL,
	"IDMagacin" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Magacin" VARCHAR(50) NOT NULL,
	"UlicaIBroj" VARCHAR(50) NULL,
	"Mesto" VARCHAR(30) NULL,
	"ProsecneCene" BOOLEAN NULL,
	"VrstaMag" VARCHAR(5) NULL,
	"KontoMag" VARCHAR(10) NULL,
	"ImeMagacionera" VARCHAR(30) NULL,
	"BrLkMagacionera" VARCHAR(20) NULL,
	"PotpisSlika" VARCHAR(250) NULL,
 CONSTRAINT "PK_Magacini" PRIMARY KEY  
(
	"IDMagacin"
)
);

CREATE TABLE public."MRP_StanjeArtikala" (

	"SifraArtikla" INTEGER NOT NULL,
	"Zalihe" NUMERIC(19,6) NOT NULL,
	"Rezervisane" NUMERIC(19,6) NOT NULL,
	"Naziv" VARCHAR(200) NULL,
	"KataloskiBroj" VARCHAR(100) NULL,
	"JedinicaMere" VARCHAR(20) NULL,
	"PoslednjaIzmena" TIMESTAMP NULL,
PRIMARY KEY  
(
	"SifraArtikla"
)
);

CREATE TABLE public."MRP_StanjeArtikala_TMP" (

	"SifraArtikla" INTEGER NOT NULL,
	"Zalihe" NUMERIC(19,6) NOT NULL,
	"Rezervisane" NUMERIC(19,6) NOT NULL,
	"Naziv" VARCHAR(200) NULL,
	"KataloskiBroj" VARCHAR(100) NULL,
	"JedinicaMere" VARCHAR(20) NULL,
PRIMARY KEY  
(
	"SifraArtikla"
)
);

CREATE TABLE public."MRP_SyncStatus" (

	"SyncKey" VARCHAR(50) NOT NULL,
	"PoslednjiSync" TIMESTAMP NULL,
	"PoslednjiSyncKorisnik" VARCHAR(100) NULL,
	"Napomena" VARCHAR(255) NULL,
PRIMARY KEY  
(
	"SyncKey"
)
);

CREATE TABLE public."Nalepnice" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDRN" INTEGER NOT NULL,
	"IDPostupka" INTEGER NOT NULL,
	"IdentBroj" VARCHAR(20) NOT NULL,
	"BarKod" VARCHAR(20) NOT NULL,
	"NazivPredmeta" VARCHAR(50) NOT NULL,
	"Komitent" VARCHAR(255) NOT NULL,
	"NazivDela" VARCHAR(250) NOT NULL,
	"BrojCrteza" VARCHAR(100) NOT NULL,
	"Materijal" VARCHAR(250) NOT NULL,
	"DatumUnosa" TIMESTAMP NOT NULL,
	"Kolicina" SMALLINT NOT NULL,
	"UkupnaKolicina" SMALLINT NULL,
	"PRN" BOOLEAN NULL,
 CONSTRAINT "PK_Nalepnice" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."Parametri za rad" (

	"Korisnik" VARCHAR(50) NOT NULL,
	"VrstaDokumenta" VARCHAR(10) NULL,
	"Telefon" VARCHAR(50) NULL,
	"Poslednji broj fakture" INTEGER NULL,
	"Poslednji broj profakture" INTEGER NULL,
	"Faktura kroz" VARCHAR(10) NULL,
	"Profaktura kroz" VARCHAR(10) NULL,
	"Faktura prefix" VARCHAR(10) NULL,
	"Profaktura prefix" VARCHAR(10) NULL,
 CONSTRAINT "aaaaaParametri za rad_PK" PRIMARY KEY  
(
	"Korisnik"
)
);

CREATE TABLE public."PDMXMLImportLog" (

	"IDLog" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"NazivFajla" VARCHAR(255) NOT NULL,
	"PutanjaFajla" VARCHAR(1024) NOT NULL,
	"ImportTimestamp" TIMESTAMP NOT NULL,
	"Uspesno" BOOLEAN NOT NULL,
	"StatusPoruka" VARCHAR(1000) NULL,
	"Kriticno" BOOLEAN NOT NULL,
PRIMARY KEY  
(
	"IDLog"
)
);

CREATE TABLE public."PredmetiVrstaPosla" (

	"IDVrstaPosla" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"VrstaPosla" VARCHAR(20) NULL,
	"Opis" VARCHAR(150) NULL,
 CONSTRAINT "PK_PredmetiVrstaPosla" PRIMARY KEY  
(
	"IDVrstaPosla"
)
);

CREATE TABLE public."PrimopredajaCrteza" (

	"IDPrimopredaje" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDCrtez" INTEGER NOT NULL,
	"DatumPredaje" TIMESTAMP NOT NULL,
	"IDRadnikPredaje" INTEGER NOT NULL,
	"IDStatusPrimopredaje" INTEGER NOT NULL,
	"DatumPromeneStatusa" TIMESTAMP NULL,
	"IDRadnikPromeneStatusa" INTEGER NULL,
	"KomentarPromeneStatusa" VARCHAR(250) NULL,
	"DatumLansiranja" TIMESTAMP NULL,
	"IDRadnikLansiranja" INTEGER NULL,
	"Napomena" VARCHAR(250) NULL,
	"Potpis" VARCHAR(30) NULL,
	"PrviUnos" TIMESTAMP NULL,
	"PoslednjaIzmena" TIMESTAMP NULL,
	"Zakljucano" BOOLEAN NULL,
PRIMARY KEY  
(
	"IDPrimopredaje"
)
);

CREATE TABLE public."PrimopredajaPDFCrteza" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDPrimopredaje" INTEGER NOT NULL,
	"LinkFajla" VARCHAR(1024) NOT NULL,
	"NazivFajla" VARCHAR(255) NOT NULL,
PRIMARY KEY  
(
	"ID"
),
 CONSTRAINT "UQ_PrimopredajaPDFCrteza_IDPrimopredaje_LinkFajla" UNIQUE  
(
	"IDPrimopredaje",
	"LinkFajla"
)
);

CREATE TABLE public."Prodavci" (

	"Sifra prodavca" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Prodavac" VARCHAR(50) NOT NULL,
	"Region" INTEGER NULL,
	"ProcenatZaObracun" DOUBLE PRECISION NULL,
	"DeljivoUGrupi" BOOLEAN NULL,
	"ImeProdavca" VARCHAR(30) NULL,
	"BrLkProdavca" VARCHAR(20) NULL,
	"LogAcc" VARCHAR(50) NULL,
	"Password" VARCHAR(20) NULL,
	"Aktivan" BOOLEAN NULL,
	"NefiskalniRN" BOOLEAN NULL,
	"Storniranje" BOOLEAN NULL,
	"PotpisSlika" VARCHAR(250) NULL,
	"OznakaTima" VARCHAR(10) NULL,
	"Telefon" VARCHAR(20) NULL,
	"Email" VARCHAR(50) NULL,
 CONSTRAINT "PK_Prodavci" PRIMARY KEY  
(
	"Sifra prodavca"
)
);

CREATE TABLE public."R_Artikli" (

	"Sifra artikla" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Kataloski broj" VARCHAR(20) NOT NULL,
	"BarKod" VARCHAR(50) NULL,
	"PLU" INTEGER NULL,
	"ExtSifra" VARCHAR(20) NULL,
	"Naziv" VARCHAR(50) NOT NULL,
	"Jedinica mere" VARCHAR(5) NULL,
	"Pakovanje" VARCHAR(10) NULL,
	"InoJm" VARCHAR(5) NULL,
	"Kutija" DOUBLE PRECISION NULL,
	"Transportno pakovanje" DOUBLE PRECISION NULL,
	"Poreklo" VARCHAR(5) NOT NULL,
	"Grupa" VARCHAR(10) NOT NULL,
	"Podgrupa" VARCHAR(10) NOT NULL,
	"Tarifa robe" VARCHAR(5) NOT NULL,
	"Tarifa usluga" VARCHAR(5) NOT NULL,
	"Uvek porez na robu" BOOLEAN NULL,
	"Uvek porez na usluge" BOOLEAN NULL,
	"VP cena" DOUBLE PRECISION NULL,
	"MP cena" DOUBLE PRECISION NULL,
	"NabDevCena" DOUBLE PRECISION NULL,
	"ProdDevCena" DOUBLE PRECISION NULL,
	"Minimalna kolicina" DOUBLE PRECISION NULL,
	"ArtTaksa" DOUBLE PRECISION NULL,
	"Odlozeno" SMALLINT NULL,
	"Neoporezivi deo" DOUBLE PRECISION NULL,
	"MaxRabatProc" DOUBLE PRECISION NULL,
	"Memo" TEXT NULL,
	"KngSifra" VARCHAR(10) NULL,
	"ArtAkciza" DOUBLE PRECISION NULL,
	"KngSifra_2" VARCHAR(10) NULL,
	"ZavTrosProiz" DOUBLE PRECISION NULL,
	"CarStopa" DOUBLE PRECISION NULL,
	"IDRaster" INTEGER NULL,
	"CarTarifa" VARCHAR(20) NULL,
	"ZemljaPorekla" VARCHAR(20) NULL,
	"Polica" VARCHAR(10) NULL,
	"INONaziv" VARCHAR(50) NULL,
	"SifDob" INTEGER NULL,
	"WebOpis" VARCHAR(255) NULL,
	"OpisArtikla" VARCHAR(50) NULL,
	"Tezina" DOUBLE PRECISION NULL,
	"PDFLink" VARCHAR(255) NULL,
	"ZaBrisanje" BOOLEAN NULL,
	"Aktivan" BOOLEAN NULL,
	"CenaZaUpisUCen" DOUBLE PRECISION NULL,
	"IDMestoIzdavanja" INTEGER NULL,
	"Proizvodjac" VARCHAR(50) NULL,
	"HPS" VARCHAR(50) NULL,
	"PotpisArt" VARCHAR(50) NULL,
	"DatumIVremeArt" TIMESTAMP NULL,
	"KolUPak" DOUBLE PRECISION NULL,
	"KLRucProc" NUMERIC(19,4) NULL,
	"OsnJM" VARCHAR(5) NULL,
	"SlikaSimbolaLink" VARCHAR(250) NULL,
	"MPKaloProc" DOUBLE PRECISION NULL,
	"WordLokacija" VARCHAR(250) NULL,
	"VPKaloProc" DOUBLE PRECISION NULL,
	"NeVodiZalihe" BOOLEAN NULL,
	"TezinaKg" DOUBLE PRECISION NULL,
	"Zapremina" DOUBLE PRECISION NULL,
	"Povrsina" DOUBLE PRECISION NULL,
	"RSort" INTEGER NULL,
	"AkcijskiRabat" DOUBLE PRECISION NULL,
	"Napomena2" VARCHAR(255) NULL,
	"IDKvalitetArtikla" INTEGER NULL,
	"Debljina" DOUBLE PRECISION NULL,
	"BBSifra artikla" INTEGER NOT NULL,
 CONSTRAINT "PK_R_Artikli" PRIMARY KEY  
(
	"Sifra artikla"
)
);

CREATE TABLE public."R_Grupa" (

	"Grupa" VARCHAR(10) NOT NULL,
	"Opis" VARCHAR(50) NOT NULL,
 CONSTRAINT "PK_R_Grupa" PRIMARY KEY  
(
	"Grupa"
)
);

CREATE TABLE public."R_Podgrupa" (

	"Podgrupa" VARCHAR(10) NOT NULL,
	"Opis" VARCHAR(50) NOT NULL,
	"GrupaVeza" VARCHAR(10) NULL,
 CONSTRAINT "PK_R_Podgrupa" PRIMARY KEY  
(
	"Podgrupa"
)
);

CREATE TABLE public."R_Poreklo" (

	"Poreklo" VARCHAR(5) NOT NULL,
	"Opis" VARCHAR(50) NOT NULL,
	"PodgrupaVeza" VARCHAR(10) NULL,
	"PopustProc" NUMERIC(19,4) NULL,
 CONSTRAINT "PK_R_Poreklo" PRIMARY KEY  
(
	"Poreklo"
)
);

CREATE TABLE public."R_Tarife" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Tarifa" VARCHAR(5) NOT NULL,
	"Osnovna stopa" DOUBLE PRECISION NULL,
	"Zeleznica stopa" DOUBLE PRECISION NULL,
	"Gradska stopa" DOUBLE PRECISION NULL,
	"Ratna stopa" DOUBLE PRECISION NULL,
	"Posebna stopa" DOUBLE PRECISION NULL,
	"Opis" TEXT NULL,
	"Vazi od" TIMESTAMP NULL,
	"Vazi do" TIMESTAMP NULL,
	"PDVGrupa" VARCHAR(10) NULL,
 CONSTRAINT "PK_R_Tarife" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."R_Vrste dokumenata" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Vrsta dokumenta" VARCHAR(5) NOT NULL,
	"Opis" VARCHAR(50) NOT NULL,
	"Ulazni" BOOLEAN NOT NULL,
	"Analiticki konto" VARCHAR(10) NULL,
	"Knjiziti analitiku" BOOLEAN NULL,
	"Sema za kontiranje" INTEGER NULL,
	"Knjiziti sintetiku" BOOLEAN NULL,
	"Prodaja sa PPP" BOOLEAN NULL,
	"Prodaja sa PPU" BOOLEAN NULL,
	"KnjizitiTKZad" BOOLEAN NULL,
	"KnjizitiTKRazd" BOOLEAN NULL,
	"TextZaReport" VARCHAR(50) NULL,
	"KnjizitiUPDVEvidenciju" BOOLEAN NULL,
	"KEPUDefZaduzenje" VARCHAR(30) NULL,
	"KEPUDefRazduzenje" VARCHAR(30) NULL,
	"InterniDokument" BOOLEAN NULL,
	"NumeracijaOd" INTEGER NULL,
	"KOTP" BOOLEAN NULL,
	"PrefiksBrojaDok" VARCHAR(5) NULL,
	"IDMagacinZaVrstuDok" INTEGER NULL,
	"KODJ" BOOLEAN NULL,
	"FR" BOOLEAN NULL,
	"UticeNaZalihe" BOOLEAN NULL,
 CONSTRAINT "PK_R_Vrste dokumenata" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."Radni fajlovi" (

	"IDBaze" INTEGER NOT NULL,
	"Firma" VARCHAR(150) NOT NULL,
	"Naziv baze" VARCHAR(255) NULL,
	"Logo" BYTEA NULL,
	"Mesto" VARCHAR(50) NULL,
	"Adresa" VARCHAR(50) NULL,
	"Telefon" VARCHAR(50) NULL,
	"Fax" VARCHAR(50) NULL,
	"Ziro racun" VARCHAR(50) NULL,
	"Delatnost" VARCHAR(255) NULL,
	"Sifra delatnosti" VARCHAR(50) NULL,
	"Opstina" VARCHAR(50) NULL,
	"Napomena" TEXT NULL,
	"Specijal" VARCHAR(50) NULL,
	"e-mail" VARCHAR(30) NULL,
	"Maticni broj" VARCHAR(50) NULL,
	"Registarski broj" VARCHAR(50) NULL,
	"Podracuni" VARCHAR(100) NULL,
	"Kasa_ProdavnicaID" INTEGER NULL,
	"Kasa_KupacID" INTEGER NULL,
	"Kasa_VrstaDokumenta" VARCHAR(5) NULL,
	"Kasa_RadniNalogID" INTEGER NULL,
	"BrDecUlKl" SMALLINT NULL,
	"BrDecIzKl" SMALLINT NULL,
	"KursDeli" BOOLEAN NULL,
	"ProveraZalihaMag" BOOLEAN NULL,
	"AutoPodelaPrihoda" BOOLEAN NULL,
	"FakturnaJeVPZaUlKl" BOOLEAN NULL,
	"KepuPoNabavnojCeni" BOOLEAN NULL,
	"TrgovackaPoKursu" BOOLEAN NULL,
	"KepuPoKursu" BOOLEAN NULL,
	"GKPoKursu" BOOLEAN NULL,
	"KontoKupac" VARCHAR(20) NULL,
	"KontoDobavljac" VARCHAR(20) NULL,
	"KnjiziRazlikeNaTK" BOOLEAN NULL,
	"KnjiziRazlikeNaKEPU" BOOLEAN NULL,
	"KnjiziRazlikeNaMPKEPU" BOOLEAN NULL,
	"GKPoKursuObrnuto" BOOLEAN NULL,
	"AutoZakRoba" BOOLEAN NULL,
	"AutoZakGK" BOOLEAN NULL,
	"StarijeOdDanaRoba" INTEGER NULL,
	"StarijeOdDanaGk" INTEGER NULL,
	"ProveraPorukaInterval" INTEGER NULL,
	"DekodirajBarKod" BOOLEAN NULL,
	"PIB" VARCHAR(20) NULL,
	"Garancija" TEXT NULL,
	"KEPUPoKNGCeni" BOOLEAN NULL,
	"PEPDV" VARCHAR(20) NULL,
	"Vlasnik" VARCHAR(50) NULL,
	"PoreskaSifra" VARCHAR(50) NULL,
	"Galeb" BOOLEAN NULL,
	"Raster" BOOLEAN NULL,
	"PG_Naziv baze" VARCHAR(255) NULL,
	"ServerZaGaleb" BOOLEAN NULL,
	"KlijentZaGaleb" BOOLEAN NULL,
	"FP_ImeStampaca" VARCHAR(50) NULL,
	"MestoIzdavanjaRacuna" VARCHAR(50) NULL,
	"Kasa_KasaID" INTEGER NULL,
	"WebAdresa" VARCHAR(50) NULL,
	"APRText" VARCHAR(250) NULL,
	"SaljiBosson" BOOLEAN NULL,
	"Kasa_Cenovnik" VARCHAR(5) NULL,
	"VPCenovnik" VARCHAR(5) NULL,
	"FooterText" VARCHAR(255) NULL,
	"Logo_Footer" BYTEA NULL,
	"RPT_Memorandum_Header" VARCHAR(64) NOT NULL,
	"RPT_Memorandum_Footer" VARCHAR(64) NOT NULL,
	"LogoFontSize" INTEGER NOT NULL,
	"PDVStatus" INTEGER NOT NULL,
	"JBKJS" VARCHAR(20) NULL,
	"ER_ApiKey" VARCHAR(50) NULL,
	"NazivFirmeNezvanicno" VARCHAR(150) NULL,
 CONSTRAINT "aaaaaRadni fajlovi_PK" PRIMARY KEY  
(
	"IDBaze"
)
);

CREATE TABLE public."RobnaDokumentaMirror" (

	"IDDok" INTEGER NOT NULL,
	"VrstaDokumenta" VARCHAR(5) NOT NULL,
	"DatumDokumenta" DATE NOT NULL,
PRIMARY KEY  
(
	"IDDok"
)
);

CREATE TABLE public."SklopoviPDMCrteza" (

	"IDSklopoviCrteza" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDCrtez" INTEGER NOT NULL,
	"KoristiSeUIDCrteza" INTEGER NOT NULL,
	"KoristiSeBrojKomada" INTEGER NOT NULL,
 CONSTRAINT "PK_SklopoviPDMCrteza" PRIMARY KEY  
(
	"IDSklopoviCrteza"
)
);

CREATE TABLE public."StatusiNacrtaPrimopredaje" (

	"IDStatusNacrtaPrimopredaje" INTEGER NOT NULL,
	"StatusNacrtaPrimopredaje" VARCHAR(100) NOT NULL,
PRIMARY KEY  
(
	"IDStatusNacrtaPrimopredaje"
)
);

CREATE TABLE public."T_Robna dokumenta" (

	"IDDok" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDFirma" INTEGER NOT NULL,
	"Ulaz" BOOLEAN NOT NULL,
	"Broj naloga" VARCHAR(20) NOT NULL,
	"Vrsta naloga" VARCHAR(5) NOT NULL,
	"Broj dokumenta" VARCHAR(20) NOT NULL,
	"Vrsta dokumenta" VARCHAR(5) NOT NULL,
	"Sifra komitenta" INTEGER NOT NULL,
	"Datum dokumenta" TIMESTAMP NOT NULL,
	"Datum knjizenja" TIMESTAMP NOT NULL,
	"Datum valute" TIMESTAMP NOT NULL,
	"Opis" VARCHAR(30) NULL,
	"Nacin otpreme" VARCHAR(30) NULL,
	"Fco" VARCHAR(30) NULL,
	"Broj izjave" VARCHAR(20) NULL,
	"Datum izjave" TIMESTAMP NULL,
	"Sifra prodavca" INTEGER NULL,
	"Nacin placanja" VARCHAR(50) NULL,
	"IDTrebZaProizvodnju" INTEGER NULL,
	"IDMagacinDOK" INTEGER NOT NULL,
	"Memo" TEXT NULL,
	"Kurs" DOUBLE PRECISION NULL,
	"IDRadniNalog" INTEGER NULL,
	"ObrKurs" DOUBLE PRECISION NULL,
	"Carina" DOUBLE PRECISION NULL,
	"Spedicija" DOUBLE PRECISION NULL,
	"OstaliZavTros" DOUBLE PRECISION NULL,
	"DevVredFak" DOUBLE PRECISION NULL,
	"Level" SMALLINT NULL,
	"IDPredmet" INTEGER NULL,
	"Zakljucano" BOOLEAN NULL,
	"IDDokUF" INTEGER NULL,
	"IDDokIF" INTEGER NULL,
	"Rezervisi" BOOLEAN NULL,
	"CarKurs" DOUBLE PRECISION NULL,
	"IDDokUSL" INTEGER NULL,
	"PovCarOsn" DOUBLE PRECISION NULL,
	"DevValuta" VARCHAR(3) NULL,
	"IDMestoIsporuke" INTEGER NULL,
	"IDRuta" INTEGER NULL,
	"IDVozac" INTEGER NULL,
	"OJ" INTEGER NULL,
	"Potpisano" BOOLEAN NULL,
	"OD" INTEGER NULL,
	"Potpis" VARCHAR(50) NULL,
	"DatumIVreme" TIMESTAMP NULL,
	"Godina" INTEGER NULL,
	"DatIVreme" TIMESTAMP NULL,
	"IDKontaktOsobe" INTEGER NULL,
	"PrimljenNovac" NUMERIC(19,4) NULL,
	"UsloviPlacanja" VARCHAR(50) NULL,
	"PrimljeniCekovi" NUMERIC(19,4) NULL,
	"PrimljenaKartica" NUMERIC(19,4) NULL,
	"IDKasa" INTEGER NULL,
	"StampanFiskalno" BOOLEAN NULL,
	"PrimljeniVirmani" NUMERIC(19,4) NULL,
	"IDDokExtBaza" INTEGER NULL,
	"DokBarKod" VARCHAR(30) NULL,
	"DokBrojKutija" SMALLINT NULL,
 CONSTRAINT "PK_T_Robna dokumenta" PRIMARY KEY  
(
	"IDDok"
)
);

CREATE TABLE public."T_Robne stavke" (

	"IDStavke" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDDok" INTEGER NOT NULL,
	"Sifra artikla" INTEGER NOT NULL,
	"Kolicina" DOUBLE PRECISION NOT NULL,
	"KG_Kolicina" DOUBLE PRECISION NULL,
	"Nabavna cena - neto" DOUBLE PRECISION NOT NULL,
	"Zavisni trosak - sopstveni" DOUBLE PRECISION NOT NULL,
	"Zavisni trosak - dobavljac" DOUBLE PRECISION NOT NULL,
	"Kalkulativna VP cena" DOUBLE PRECISION NOT NULL,
	"Kalkulativna MP cena" DOUBLE PRECISION NOT NULL,
	"Stvarna VP cena" DOUBLE PRECISION NOT NULL,
	"Stvarna MP cena" DOUBLE PRECISION NOT NULL,
	"Taksa" DOUBLE PRECISION NULL,
	"Obracunat porez na ulazu - roba" BOOLEAN NOT NULL,
	"Tarifa - roba - ulaz" VARCHAR(5) NOT NULL,
	"Obracunat porez na usluge" BOOLEAN NOT NULL,
	"Tarifa - usluge - izlaz" VARCHAR(5) NOT NULL,
	"Obracunat  porez na robu" BOOLEAN NOT NULL,
	"Tarifa - roba - Izlaz" VARCHAR(5) NOT NULL,
	"RabatProc" DOUBLE PRECISION NOT NULL,
	"KasaProc" DOUBLE PRECISION NOT NULL,
	"Odlozeno" SMALLINT NULL,
	"Neoporezivi deo" DOUBLE PRECISION NULL,
	"Akciza" DOUBLE PRECISION NULL,
	"FiksniPorez" DOUBLE PRECISION NULL,
	"DevNabCena" DOUBLE PRECISION NULL,
	"IDMagacin" INTEGER NOT NULL,
	"KNGCena" DOUBLE PRECISION NULL,
	"CarStopa" DOUBLE PRECISION NULL,
	"IDPredmetStavka" INTEGER NOT NULL,
	"OpisStavke" VARCHAR(50) NULL,
	"ID_PO" INTEGER NULL,
	"PakPoOsnJM" DOUBLE PRECISION NULL,
	"IDPrepisaneStavke" INTEGER NULL,
	"ProknjizenoIzProfUIF" BOOLEAN NULL,
	"IDStavkeTrebovanja" INTEGER NULL,
 CONSTRAINT "PK_T_Robne stavke" PRIMARY KEY  
(
	"IDStavke"
)
);

CREATE TABLE public."tmp_T_KontroleNaFormi" (

	"ImeForme" VARCHAR(50) NOT NULL,
	"ImeKontrole" VARCHAR(50) NOT NULL,
	"TipKontrole" VARCHAR(50) NULL,
 CONSTRAINT "aaaaatmp_T_KontroleNaFormi_PK" PRIMARY KEY  
(
	"ImeForme",
	"ImeKontrole"
)
);

CREATE TABLE public."tOperacijeFix" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"RJgrupaRC" VARCHAR(5) NOT NULL,
	"NazivGrupeRC" VARCHAR(50) NOT NULL,
	"Napomena" VARCHAR(255) NULL,
	"IDRadneJedinice" VARCHAR(5) NOT NULL,
	"BezPostupka" BOOLEAN NULL,
	"ZnacajneOperacijeZaZavrsen" BOOLEAN NULL,
	"KoristiPrioritet" BOOLEAN NOT NULL
);

CREATE TABLE public."tPDM" (

	"IDStavkePDM" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDRN" INTEGER NOT NULL,
	"PozicijaPDM" VARCHAR(50) NOT NULL,
	"OperacijaPDM" INTEGER NULL,
	"RJgrupaRC" VARCHAR(5) NOT NULL,
	"NazivP" VARCHAR(60) NULL,
	"BrojCrtezaP" VARCHAR(50) NULL,
	"Komada" INTEGER NULL,
	"DIVUnosa" TIMESTAMP NOT NULL,
	"DIVIspravke" TIMESTAMP NOT NULL,
	"SifraRadnika" INTEGER NOT NULL,
 CONSTRAINT "PK_tPDM" PRIMARY KEY  
(
	"IDStavkePDM"
)
);

CREATE TABLE public."tPLP" (

	"IDStavkePLP" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDRN" INTEGER NOT NULL,
	"PozicijaPLP" VARCHAR(50) NOT NULL,
	"RJgrupaRC" VARCHAR(5) NOT NULL,
	"Materijal" VARCHAR(50) NULL,
	"DimenzijaMaterijala" VARCHAR(50) NULL,
	"JM" VARCHAR(5) NULL,
	"TezinaJed" DOUBLE PRECISION NULL,
	"Komada" INTEGER NULL,
	"BrojPozicije" VARCHAR(50) NULL,
	"DIVUnosa" TIMESTAMP NOT NULL,
	"DIVIspravke" TIMESTAMP NOT NULL,
	"SifraRadnika" INTEGER NOT NULL,
 CONSTRAINT "PK_tPLP" PRIMARY KEY  
(
	"IDStavkePLP"
)
);

CREATE TABLE public."tPND" (

	"IDStavkePND" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDRN" INTEGER NOT NULL,
	"PozicijaPND" VARCHAR(50) NOT NULL,
	"OperacijaPND" INTEGER NULL,
	"RJgrupaRC" VARCHAR(5) NOT NULL,
	"NazivDela" VARCHAR(80) NOT NULL,
	"Komada" DOUBLE PRECISION NULL,
	"Napomena" VARCHAR(50) NULL,
	"DIVUnosa" TIMESTAMP NOT NULL,
	"DIVIspravke" TIMESTAMP NOT NULL,
	"SifraRadnika" INTEGER NOT NULL,
 CONSTRAINT "PK_tPND" PRIMARY KEY  
(
	"IDStavkePND"
)
);

CREATE TABLE public."tPristupMasini" (

	"IDPristupMasini" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"SifraRadnika" INTEGER NOT NULL,
	"RJgrupaRC" VARCHAR(5) NOT NULL,
	"Napomena" VARCHAR(250) NULL,
 CONSTRAINT "PK_tPristupMasini" PRIMARY KEY  
(
	"IDPristupMasini"
)
);

CREATE TABLE public."tR_Grupa" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Grupa" VARCHAR(10) NOT NULL,
	"Opis" VARCHAR(50) NULL,
 CONSTRAINT "PK_tR_Grupa" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."tRadneJedinice" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDRadneJedinice" VARCHAR(5) NOT NULL,
	"RadnaJedinica" VARCHAR(50) NOT NULL,
 CONSTRAINT "PK_tRadneJedinice" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."tRNNDKomponente" (

	"IDNDKomponente" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDRN" INTEGER NOT NULL,
	"SifraArtikla" INTEGER NOT NULL,
	"BrojKomada" INTEGER NOT NULL,
	"Napomena" VARCHAR(255) NULL,
PRIMARY KEY  
(
	"IDNDKomponente"
)
);

CREATE TABLE public."tStavkeRNSlike" (

	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IDStavkeRN" INTEGER NOT NULL,
	"LinkSlika" VARCHAR(250) NOT NULL,
	"ImeFajla" VARCHAR(50) NOT NULL,
 CONSTRAINT "PK_tStavkeRNSlike" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."tTehPostupakBackup" (

	"IDPostupka" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"SifraRadnika" INTEGER NOT NULL,
	"IDPredmet" INTEGER NOT NULL,
	"IdentBroj" VARCHAR(50) NOT NULL,
	"Varijanta" INTEGER NOT NULL,
	"PrnTimer" INTEGER NULL,
	"DatumIVremeUnosa" TIMESTAMP NOT NULL,
	"Operacija" INTEGER NOT NULL,
	"RJgrupaRC" VARCHAR(5) NOT NULL,
	"Toznaka" VARCHAR(50) NOT NULL,
	"Komada" INTEGER NOT NULL,
	"Potpis" VARCHAR(50) NULL,
	"SimbolRadnik" BOOLEAN NULL,
	"SimbolPostupak" BOOLEAN NULL,
	"SimbolOperacija" BOOLEAN NULL,
	"DatumIVremeZavrsetka" TIMESTAMP NULL,
	"ZavrsenPostupak" BOOLEAN NULL,
	"Napomena" TEXT NULL,
	"IDRN" INTEGER NOT NULL,
	"IDVrstaKvaliteta" INTEGER NOT NULL,
	"DoradaOperacije" INTEGER NULL,
	"DatumIspravke" TIMESTAMP NULL,
	"NapomenaIspravke" VARCHAR(500) NULL
);

CREATE TABLE public."UplatniRacuni" (

	"IDFirma" INTEGER NOT NULL,
	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"UplatniRacun" VARCHAR(50) NOT NULL,
	"NazivBanke" VARCHAR(50) NULL,
	"Default" BOOLEAN NOT NULL,
	"Rbr" SMALLINT NOT NULL,
	"KodZemlje" VARCHAR(20) NULL,
	"OznakaBanke" VARCHAR(20) NULL,
 CONSTRAINT "aaaaaUplatniRacuni_PK" PRIMARY KEY  
(
	"ID"
)
);

CREATE TABLE public."VrednostiZaKombo" (

	"Kolona" VARCHAR(64) NOT NULL,
	"Vrednost" VARCHAR(255) NOT NULL,
 CONSTRAINT "PK_TabelaVrednostiZaKombo" PRIMARY KEY  
(
	"Kolona",
	"Vrednost"
)
);

CREATE TABLE public."Vrsta naloga" (

	"Vrsta naloga" VARCHAR(5) NOT NULL,
	"Opis" VARCHAR(50) NULL,
 CONSTRAINT "aaaaaVrsta naloga_PK" PRIMARY KEY  
(
	"Vrsta naloga"
)
);

CREATE TABLE public."Vrste sifara" (

	"Vrsta sifre" VARCHAR(10) NOT NULL,
	"Opis" VARCHAR(50) NULL,
 CONSTRAINT "aaaaaVrste sifara_PK" PRIMARY KEY  
(
	"Vrsta sifre"
)
);

-- === Podrazumevane vrednosti ===

ALTER TABLE public."_Dnevnik" ALTER COLUMN "DIV" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."_RegAccess" ALTER COLUMN "Login_Time" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."_RegApps" ALTER COLUMN "Disabled" SET DEFAULT false;
ALTER TABLE public."_RegApps" ALTER COLUMN "PrviUnos" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."_RegApps" ALTER COLUMN "PoslednjaIzmena" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."_RegAppsFiles" ALTER COLUMN "Install" SET DEFAULT false;
ALTER TABLE public."_RegAppsFiles" ALTER COLUMN "Update" SET DEFAULT false;
ALTER TABLE public."_RegAppsFiles" ALTER COLUMN "PrviUnos" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."_RegAppsFiles" ALTER COLUMN "PoslednjaIzmena" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."_RegUsers" ALTER COLUMN "Disabled" SET DEFAULT false;
ALTER TABLE public."_RegUsers" ALTER COLUMN "PrviUnos" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."_RegUsers" ALTER COLUMN "PoslednjaIzmena" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."_RegUsersApps" ALTER COLUMN "Disabled" SET DEFAULT false;
ALTER TABLE public."_RegUsersApps" ALTER COLUMN "EXCL" SET DEFAULT false;
ALTER TABLE public."_RegUsersApps" ALTER COLUMN "RUNTIME" SET DEFAULT false;
ALTER TABLE public."_RegUsersApps" ALTER COLUMN "PrviUnos" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."_RegUsersApps" ALTER COLUMN "PoslednjaIzmena" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."_Rev" ALTER COLUMN "APP" SET DEFAULT 'DB';
ALTER TABLE public."_Rev" ALTER COLUMN "Ver" SET DEFAULT '-';
ALTER TABLE public."_Rev" ALTER COLUMN "VerDatum" SET DEFAULT (CURRENT_DATE::timestamp);
ALTER TABLE public."_Rev" ALTER COLUMN "Tema" SET DEFAULT '-';
ALTER TABLE public."_Rev" ALTER COLUMN "Uradjeno" SET DEFAULT true;
ALTER TABLE public."_Rev" ALTER COLUMN "Firma" SET DEFAULT '-';
ALTER TABLE public."_Rev" ALTER COLUMN "DIVUnos" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."_Rev" ALTER COLUMN "SubRev" SET DEFAULT 0;
ALTER TABLE public."BBDefUser" ALTER COLUMN "DefaultGodina" SET DEFAULT EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER;
ALTER TABLE public."BBDefUser" ALTER COLUMN "DefaultOJ" SET DEFAULT 0;
ALTER TABLE public."BBDefUser" ALTER COLUMN "DefaultOD" SET DEFAULT 0;
ALTER TABLE public."BBDefUser" ALTER COLUMN "UnlockGodina" SET DEFAULT false;
ALTER TABLE public."BBDefUser" ALTER COLUMN "UnlockOJ" SET DEFAULT false;
ALTER TABLE public."BBDefUser" ALTER COLUMN "UnlockOD" SET DEFAULT false;
ALTER TABLE public."BBDefUser" ALTER COLUMN "Level" SET DEFAULT 0;
ALTER TABLE public."BBDefUser" ALTER COLUMN "MaxLevel" SET DEFAULT 0;
ALTER TABLE public."BBPravaPristupa" ALTER COLUMN "Visible" SET DEFAULT true;
ALTER TABLE public."BBPravaPristupa" ALTER COLUMN "Locked" SET DEFAULT false;
ALTER TABLE public."BBPravaPristupa" ALTER COLUMN "Enabled" SET DEFAULT true;
ALTER TABLE public."Cenovnik" ALTER COLUMN "Sifra artikla" SET DEFAULT 0;
ALTER TABLE public."Cenovnik" ALTER COLUMN "Cena" SET DEFAULT 0;
ALTER TABLE public."Cenovnik" ALTER COLUMN "CenaBezPDV" SET DEFAULT 0;
ALTER TABLE public."Cenovnik" ALTER COLUMN "Taksa" SET DEFAULT 0;
ALTER TABLE public."Cenovnik" ALTER COLUMN "Prn" SET DEFAULT true;
ALTER TABLE public."Cenovnik" ALTER COLUMN "CenaSaPDV" SET DEFAULT 0;
ALTER TABLE public."Cenovnik" ALTER COLUMN "CheckCenaSaPDV" SET DEFAULT false;
ALTER TABLE public."Cenovnik" ALTER COLUMN "ZakCen" SET DEFAULT false;
ALTER TABLE public."CFG_Global" ALTER COLUMN "IDFirma" SET DEFAULT 0;
ALTER TABLE public."CFG_Sys" ALTER COLUMN "DIVUnos" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."Info" ALTER COLUMN "ID" SET DEFAULT 0;
ALTER TABLE public."Info" ALTER COLUMN "Prijem" SET DEFAULT false;
ALTER TABLE public."Komitenti" ALTER COLUMN "Region" SET DEFAULT 0;
ALTER TABLE public."Komitenti" ALTER COLUMN "Vrsta sifre" SET DEFAULT 'KUPDOB';
ALTER TABLE public."Komitenti" ALTER COLUMN "Sifra prodavca" SET DEFAULT 0;
ALTER TABLE public."Komitenti" ALTER COLUMN "RabatKomitenta" SET DEFAULT 0;
ALTER TABLE public."Komitenti" ALTER COLUMN "PDVStatus" SET DEFAULT 0;
ALTER TABLE public."Komitenti" ALTER COLUMN "Odlozeno" SET DEFAULT 0;
ALTER TABLE public."Komitenti" ALTER COLUMN "IDRuta" SET DEFAULT 0;
ALTER TABLE public."Komitenti" ALTER COLUMN "IDVozac" SET DEFAULT 0;
ALTER TABLE public."Komitenti" ALTER COLUMN "IDUplatniRacun" SET DEFAULT 0;
ALTER TABLE public."Komitenti" ALTER COLUMN "FakturisanjePoMestimaIsporuke" SET DEFAULT true;
ALTER TABLE public."Komitenti" ALTER COLUMN "ProcenatProvizije" SET DEFAULT 0;
ALTER TABLE public."Komitenti" ALTER COLUMN "FiktRabatKomitenta" SET DEFAULT 0;
ALTER TABLE public."Komitenti" ALTER COLUMN "DatumIVremeKom" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."Komitenti" ALTER COLUMN "ProveraDuga" SET DEFAULT false;
ALTER TABLE public."Komitenti" ALTER COLUMN "KreditLimit" SET DEFAULT 0;
ALTER TABLE public."Komitenti" ALTER COLUMN "NeProveravajPIB" SET DEFAULT false;
ALTER TABLE public."Komitenti" ALTER COLUMN "NewsLetter" SET DEFAULT false;
ALTER TABLE public."Komitenti" ALTER COLUMN "PostaNaDruguAdresu" SET DEFAULT false;
ALTER TABLE public."Komitenti" ALTER COLUMN "KLRucProc" SET DEFAULT 0;
ALTER TABLE public."Komitenti" ALTER COLUMN "NePrikazatiUPregledu" SET DEFAULT false;
ALTER TABLE public."Komitenti" ALTER COLUMN "ER_XMLSaPopustomPoArtiklu" SET DEFAULT false;
ALTER TABLE public."Komitenti" ALTER COLUMN "CRF" SET DEFAULT false;
ALTER TABLE public."KomponentePDMCrteza" ALTER COLUMN "PotrebnoKomada" SET DEFAULT 1;
ALTER TABLE public."Magacini" ALTER COLUMN "IDFirma" SET DEFAULT 0;
ALTER TABLE public."Magacini" ALTER COLUMN "ProsecneCene" SET DEFAULT false;
ALTER TABLE public."MRP_Potrebe" ALTER COLUMN "Status" SET DEFAULT 0;
ALTER TABLE public."MRP_Potrebe" ALTER COLUMN "DIVUnosa" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."MRP_Potrebe" ALTER COLUMN "PlaniranaKolicina" SET DEFAULT 0;
ALTER TABLE public."MRP_PotrebeStavke" ALTER COLUMN "DIVUnosa" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."MRP_PotrebeStavke" ALTER COLUMN "StatusStavke" SET DEFAULT 0;
ALTER TABLE public."MRP_PotrebeStavke" ALTER COLUMN "KolicinaRezervisano" SET DEFAULT 0;
ALTER TABLE public."MRP_PotrebeStavke" ALTER COLUMN "KolicinaZaNabavku" SET DEFAULT 0;
ALTER TABLE public."MRP_StanjeArtikala" ALTER COLUMN "Zalihe" SET DEFAULT 0;
ALTER TABLE public."MRP_StanjeArtikala" ALTER COLUMN "Rezervisane" SET DEFAULT 0;
ALTER TABLE public."MRP_StanjeArtikala" ALTER COLUMN "PoslednjaIzmena" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."MRP_StanjeArtikala_TMP" ALTER COLUMN "Zalihe" SET DEFAULT 0;
ALTER TABLE public."MRP_StanjeArtikala_TMP" ALTER COLUMN "Rezervisane" SET DEFAULT 0;
ALTER TABLE public."NacrtPrimopredaje" ALTER COLUMN "DatumNacrta" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."NacrtPrimopredaje" ALTER COLUMN "IDStatusNacrtaPrimopredaje" SET DEFAULT 0;
ALTER TABLE public."NacrtPrimopredaje" ALTER COLUMN "PrviUnos" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."NacrtPrimopredaje" ALTER COLUMN "PoslednjaIzmena" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."NacrtPrimopredaje" ALTER COLUMN "BrojNacrta" SET DEFAULT N'';
ALTER TABLE public."NacrtPrimopredaje" ALTER COLUMN "Zakljucano" SET DEFAULT false;
ALTER TABLE public."NacrtPrimopredaje" ALTER COLUMN "TipNacrta" SET DEFAULT 0;
ALTER TABLE public."NacrtPrimopredajeStavke" ALTER COLUMN "PrviUnos" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."NacrtPrimopredajeStavke" ALTER COLUMN "PoslednjaIzmena" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."NacrtPrimopredajeStavke" ALTER COLUMN "KolicinaZaIzradu" SET DEFAULT 1;
ALTER TABLE public."NacrtPrimopredajeStavke" ALTER COLUMN "IsGlavni" SET DEFAULT false;
ALTER TABLE public."NacrtPrimopredajeStavke" ALTER COLUMN "PredProveraDuplikat" SET DEFAULT false;
ALTER TABLE public."NacrtPrimopredajeStavke" ALTER COLUMN "IskljuciPrimopredaju" SET DEFAULT false;
ALTER TABLE public."NacrtPrimopredajeStavke" ALTER COLUMN "OdlukaAkcija" SET DEFAULT 0;
ALTER TABLE public."NacrtPrimopredajeStavke" ALTER COLUMN "KolicinaDefinisanaUCrtezu" SET DEFAULT 0;
ALTER TABLE public."Nalepnice" ALTER COLUMN "PRN" SET DEFAULT true;
ALTER TABLE public."Parametri za rad" ALTER COLUMN "Poslednji broj fakture" SET DEFAULT 0;
ALTER TABLE public."Parametri za rad" ALTER COLUMN "Poslednji broj profakture" SET DEFAULT 0;
ALTER TABLE public."PDM_PDFCrtezi" ALTER COLUMN "DatumUnosa" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."PDM_PDFCrtezi" ALTER COLUMN "KorisnikUnosa" SET DEFAULT (SESSION_USER)::text;
ALTER TABLE public."PDM_Planiranje" ALTER COLUMN "StatusPlaniranja" SET DEFAULT 0;
ALTER TABLE public."PDM_Planiranje" ALTER COLUMN "DatumPlaniranja" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."PDM_Planiranje" ALTER COLUMN "PrviUnos" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."PDM_Planiranje" ALTER COLUMN "PoslednjaIzmena" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."PDM_PlaniranjeStavke" ALTER COLUMN "OdlukaAkcija" SET DEFAULT 0;
ALTER TABLE public."PDM_PlaniranjeStavke" ALTER COLUMN "Rezervisano" SET DEFAULT 0;
ALTER TABLE public."PDM_PlaniranjeStavke" ALTER COLUMN "ZaNabavku" SET DEFAULT 0;
ALTER TABLE public."PDM_PlaniranjeStavke" ALTER COLUMN "JeRucnaStavka" SET DEFAULT false;
ALTER TABLE public."PDM_PlaniranjeStavke" ALTER COLUMN "IskljuciNabavku" SET DEFAULT false;
ALTER TABLE public."PDMCrtezi" ALTER COLUMN "Revizija" SET DEFAULT N'A';
ALTER TABLE public."PDMCrtezi" ALTER COLUMN "Kolicina" SET DEFAULT 1;
ALTER TABLE public."PDMCrtezi" ALTER COLUMN "IDStatusCrteza" SET DEFAULT 0;
ALTER TABLE public."PDMCrtezi" ALTER COLUMN "Nabavka" SET DEFAULT false;
ALTER TABLE public."PDMXMLImportLog" ALTER COLUMN "ImportTimestamp" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."PDMXMLImportLog" ALTER COLUMN "Kriticno" SET DEFAULT false;
ALTER TABLE public."Predmeti" ALTER COLUMN "DatumOtvaranja" SET DEFAULT (CURRENT_DATE::timestamp);
ALTER TABLE public."Predmeti" ALTER COLUMN "IDProdavac" SET DEFAULT 0;
ALTER TABLE public."Predmeti" ALTER COLUMN "NabavnaVrednost" SET DEFAULT 0;
ALTER TABLE public."Predmeti" ALTER COLUMN "Carina" SET DEFAULT 0;
ALTER TABLE public."Predmeti" ALTER COLUMN "Spedicija" SET DEFAULT 0;
ALTER TABLE public."Predmeti" ALTER COLUMN "Prevoz" SET DEFAULT 0;
ALTER TABLE public."Predmeti" ALTER COLUMN "Ostalo" SET DEFAULT 0;
ALTER TABLE public."Predmeti" ALTER COLUMN "InoDobavljac" SET DEFAULT 0;
ALTER TABLE public."Predmeti" ALTER COLUMN "kurs" SET DEFAULT 0;
ALTER TABLE public."Predmeti" ALTER COLUMN "IDVrstaPosla" SET DEFAULT 0;
ALTER TABLE public."Predmeti" ALTER COLUMN "DatumIVreme" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."PrimopredajaCrteza" ALTER COLUMN "IDStatusPrimopredaje" SET DEFAULT 0;
ALTER TABLE public."PrimopredajaCrteza" ALTER COLUMN "PrviUnos" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."PrimopredajaCrteza" ALTER COLUMN "PoslednjaIzmena" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."PrimopredajaCrteza" ALTER COLUMN "Zakljucano" SET DEFAULT false;
ALTER TABLE public."Prodavci" ALTER COLUMN "Region" SET DEFAULT 0;
ALTER TABLE public."Prodavci" ALTER COLUMN "ProcenatZaObracun" SET DEFAULT 0;
ALTER TABLE public."Prodavci" ALTER COLUMN "DeljivoUGrupi" SET DEFAULT false;
ALTER TABLE public."Prodavci" ALTER COLUMN "Aktivan" SET DEFAULT true;
ALTER TABLE public."Prodavci" ALTER COLUMN "NefiskalniRN" SET DEFAULT false;
ALTER TABLE public."Prodavci" ALTER COLUMN "Storniranje" SET DEFAULT false;
ALTER TABLE public."Prodavci" ALTER COLUMN "OznakaTima" SET DEFAULT '000';
ALTER TABLE public."R_Artikli" ALTER COLUMN "Kataloski broj" SET DEFAULT '-';
ALTER TABLE public."R_Artikli" ALTER COLUMN "PLU" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "Kutija" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "Transportno pakovanje" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "Poreklo" SET DEFAULT '0';
ALTER TABLE public."R_Artikli" ALTER COLUMN "Podgrupa" SET DEFAULT '0';
ALTER TABLE public."R_Artikli" ALTER COLUMN "Tarifa robe" SET DEFAULT '3';
ALTER TABLE public."R_Artikli" ALTER COLUMN "Tarifa usluga" SET DEFAULT '1';
ALTER TABLE public."R_Artikli" ALTER COLUMN "Uvek porez na robu" SET DEFAULT true;
ALTER TABLE public."R_Artikli" ALTER COLUMN "Uvek porez na usluge" SET DEFAULT false;
ALTER TABLE public."R_Artikli" ALTER COLUMN "VP cena" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "MP cena" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "NabDevCena" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "ProdDevCena" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "Minimalna kolicina" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "ArtTaksa" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "Odlozeno" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "Neoporezivi deo" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "MaxRabatProc" SET DEFAULT 100;
ALTER TABLE public."R_Artikli" ALTER COLUMN "KngSifra" SET DEFAULT '0';
ALTER TABLE public."R_Artikli" ALTER COLUMN "ArtAkciza" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "KngSifra_2" SET DEFAULT '0';
ALTER TABLE public."R_Artikli" ALTER COLUMN "ZavTrosProiz" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "CarStopa" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "IDRaster" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "SifDob" SET DEFAULT 1;
ALTER TABLE public."R_Artikli" ALTER COLUMN "Tezina" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "ZaBrisanje" SET DEFAULT false;
ALTER TABLE public."R_Artikli" ALTER COLUMN "Aktivan" SET DEFAULT true;
ALTER TABLE public."R_Artikli" ALTER COLUMN "CenaZaUpisUCen" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "IDMestoIzdavanja" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "HPS" SET DEFAULT 'O';
ALTER TABLE public."R_Artikli" ALTER COLUMN "DatumIVremeArt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."R_Artikli" ALTER COLUMN "KolUPak" SET DEFAULT 1;
ALTER TABLE public."R_Artikli" ALTER COLUMN "KLRucProc" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "MPKaloProc" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "VPKaloProc" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "NeVodiZalihe" SET DEFAULT false;
ALTER TABLE public."R_Artikli" ALTER COLUMN "TezinaKg" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "Zapremina" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "Povrsina" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "RSort" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "AkcijskiRabat" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "IDKvalitetArtikla" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "Debljina" SET DEFAULT 0;
ALTER TABLE public."R_Artikli" ALTER COLUMN "BBSifra artikla" SET DEFAULT 0;
ALTER TABLE public."R_Podgrupa" ALTER COLUMN "GrupaVeza" SET DEFAULT '0';
ALTER TABLE public."R_Poreklo" ALTER COLUMN "PodgrupaVeza" SET DEFAULT '0';
ALTER TABLE public."R_Poreklo" ALTER COLUMN "PopustProc" SET DEFAULT 0;
ALTER TABLE public."R_Tarife" ALTER COLUMN "Osnovna stopa" SET DEFAULT 0;
ALTER TABLE public."R_Tarife" ALTER COLUMN "Zeleznica stopa" SET DEFAULT 0;
ALTER TABLE public."R_Tarife" ALTER COLUMN "Gradska stopa" SET DEFAULT 0;
ALTER TABLE public."R_Tarife" ALTER COLUMN "Ratna stopa" SET DEFAULT 0;
ALTER TABLE public."R_Tarife" ALTER COLUMN "Posebna stopa" SET DEFAULT 0;
ALTER TABLE public."R_Tarife" ALTER COLUMN "PDVGrupa" SET DEFAULT 'VISA';
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "Ulazni" SET DEFAULT false;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "Knjiziti analitiku" SET DEFAULT false;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "Sema za kontiranje" SET DEFAULT 0;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "Knjiziti sintetiku" SET DEFAULT false;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "Prodaja sa PPP" SET DEFAULT false;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "Prodaja sa PPU" SET DEFAULT true;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "KnjizitiTKZad" SET DEFAULT false;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "KnjizitiTKRazd" SET DEFAULT false;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "KnjizitiUPDVEvidenciju" SET DEFAULT true;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "InterniDokument" SET DEFAULT false;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "NumeracijaOd" SET DEFAULT 0;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "KOTP" SET DEFAULT false;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "IDMagacinZaVrstuDok" SET DEFAULT 0;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "KODJ" SET DEFAULT false;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "FR" SET DEFAULT false;
ALTER TABLE public."R_Vrste dokumenata" ALTER COLUMN "UticeNaZalihe" SET DEFAULT true;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "Specijal" SET DEFAULT 'DEFAULT';
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "Kasa_ProdavnicaID" SET DEFAULT 0;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "Kasa_KupacID" SET DEFAULT 0;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "Kasa_VrstaDokumenta" SET DEFAULT 'MP1';
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "Kasa_RadniNalogID" SET DEFAULT 0;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "BrDecUlKl" SET DEFAULT 2;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "BrDecIzKl" SET DEFAULT 2;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "KursDeli" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "ProveraZalihaMag" SET DEFAULT true;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "AutoPodelaPrihoda" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "FakturnaJeVPZaUlKl" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "KepuPoNabavnojCeni" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "TrgovackaPoKursu" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "KepuPoKursu" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "GKPoKursu" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "KontoKupac" SET DEFAULT '2040';
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "KontoDobavljac" SET DEFAULT '4350';
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "KnjiziRazlikeNaTK" SET DEFAULT true;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "KnjiziRazlikeNaKEPU" SET DEFAULT true;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "KnjiziRazlikeNaMPKEPU" SET DEFAULT true;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "GKPoKursuObrnuto" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "AutoZakRoba" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "AutoZakGK" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "StarijeOdDanaRoba" SET DEFAULT 7;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "StarijeOdDanaGk" SET DEFAULT 7;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "ProveraPorukaInterval" SET DEFAULT 0;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "DekodirajBarKod" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "KEPUPoKNGCeni" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "Galeb" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "Raster" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "ServerZaGaleb" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "KlijentZaGaleb" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "FP_ImeStampaca" SET DEFAULT 'GALEB01';
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "MestoIzdavanjaRacuna" SET DEFAULT 'Beograd';
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "Kasa_KasaID" SET DEFAULT 0;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "SaljiBosson" SET DEFAULT false;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "Kasa_Cenovnik" SET DEFAULT 'MP1';
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "VPCenovnik" SET DEFAULT 'STDCN';
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "RPT_Memorandum_Header" SET DEFAULT N'Memorandum_Header_STD';
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "RPT_Memorandum_Footer" SET DEFAULT N'Memorandum_Footer_STD';
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "LogoFontSize" SET DEFAULT 24;
ALTER TABLE public."Radni fajlovi" ALTER COLUMN "PDVStatus" SET DEFAULT 0;
ALTER TABLE public."RobneStavkeMirror" ALTER COLUMN "KolicinaUlaz" SET DEFAULT 0;
ALTER TABLE public."RobneStavkeMirror" ALTER COLUMN "KolicinaIzlaz" SET DEFAULT 0;
ALTER TABLE public."RobneStavkeMirror" ALTER COLUMN "PoslednjaIzmena" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."SklopoviPDMCrteza" ALTER COLUMN "KoristiSeBrojKomada" SET DEFAULT 1;
ALTER TABLE public."T_Planer" ALTER COLUMN "IDFirma" SET DEFAULT 0;
ALTER TABLE public."T_Planer" ALTER COLUMN "Subject" SET DEFAULT N'-';
ALTER TABLE public."T_Planer" ALTER COLUMN "Prioritet" SET DEFAULT 0;
ALTER TABLE public."T_Planer" ALTER COLUMN "RepeatCode" SET DEFAULT 'JEDNOM';
ALTER TABLE public."T_Planer" ALTER COLUMN "CheckUradjeno" SET DEFAULT false;
ALTER TABLE public."T_Planer" ALTER COLUMN "AutoExec" SET DEFAULT false;
ALTER TABLE public."T_Planer" ALTER COLUMN "DIVPrviUnos" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."T_Planer" ALTER COLUMN "DIVPoslednjaIzmena" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "IDFirma" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "Ulaz" SET DEFAULT false;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "Sifra komitenta" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "Sifra prodavca" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "IDTrebZaProizvodnju" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "IDMagacinDOK" SET DEFAULT 1;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "Kurs" SET DEFAULT 1;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "IDRadniNalog" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "ObrKurs" SET DEFAULT 1;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "Carina" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "Spedicija" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "OstaliZavTros" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "DevVredFak" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "Level" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "IDPredmet" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "Zakljucano" SET DEFAULT false;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "IDDokUF" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "IDDokIF" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "Rezervisi" SET DEFAULT false;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "CarKurs" SET DEFAULT 1;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "IDDokUSL" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "PovCarOsn" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "DevValuta" SET DEFAULT 'DIN';
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "IDMestoIsporuke" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "IDRuta" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "IDVozac" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "OJ" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "Potpisano" SET DEFAULT false;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "OD" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "DatumIVreme" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "Godina" SET DEFAULT EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "DatIVreme" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "IDKontaktOsobe" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "PrimljenNovac" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "PrimljeniCekovi" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "PrimljenaKartica" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "IDKasa" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "StampanFiskalno" SET DEFAULT false;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "PrimljeniVirmani" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "IDDokExtBaza" SET DEFAULT 0;
ALTER TABLE public."T_Robna dokumenta" ALTER COLUMN "DokBrojKutija" SET DEFAULT 1;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "IDDok" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Sifra artikla" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Kolicina" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "KG_Kolicina" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Nabavna cena - neto" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Zavisni trosak - sopstveni" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Zavisni trosak - dobavljac" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Kalkulativna VP cena" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Kalkulativna MP cena" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Stvarna VP cena" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Stvarna MP cena" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Taksa" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Obracunat porez na ulazu - roba" SET DEFAULT true;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Tarifa - roba - ulaz" SET DEFAULT '3';
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Obracunat porez na usluge" SET DEFAULT true;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Tarifa - usluge - izlaz" SET DEFAULT '1';
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Obracunat  porez na robu" SET DEFAULT true;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Tarifa - roba - Izlaz" SET DEFAULT '3';
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "RabatProc" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "KasaProc" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Odlozeno" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Neoporezivi deo" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "Akciza" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "FiksniPorez" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "DevNabCena" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "IDMagacin" SET DEFAULT 1;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "KNGCena" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "CarStopa" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "IDPredmetStavka" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "ID_PO" SET DEFAULT 0;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "PakPoOsnJM" SET DEFAULT 1;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "ProknjizenoIzProfUIF" SET DEFAULT false;
ALTER TABLE public."T_Robne stavke" ALTER COLUMN "IDStavkeTrebovanja" SET DEFAULT 0;
ALTER TABLE public."tLansiranRN" ALTER COLUMN "IDRN" SET DEFAULT 0;
ALTER TABLE public."tLansiranRN" ALTER COLUMN "Lansiran" SET DEFAULT false;
ALTER TABLE public."tLansiranRN" ALTER COLUMN "DIVUnos" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tLansiranRN" ALTER COLUMN "SifraRadnikaUnos" SET DEFAULT 0;
ALTER TABLE public."tLansiranRN" ALTER COLUMN "DIVIspravke" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tLokacijeDelova" ALTER COLUMN "IDRN" SET DEFAULT 0;
ALTER TABLE public."tLokacijeDelova" ALTER COLUMN "IDPredmet" SET DEFAULT 0;
ALTER TABLE public."tLokacijeDelova" ALTER COLUMN "IDVrstaKvaliteta" SET DEFAULT 0;
ALTER TABLE public."tLokacijeDelova" ALTER COLUMN "IDPozicija" SET DEFAULT 0;
ALTER TABLE public."tLokacijeDelova" ALTER COLUMN "SifraRadnika" SET DEFAULT 0;
ALTER TABLE public."tLokacijeDelova" ALTER COLUMN "Datum" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tLokacijeDelova" ALTER COLUMN "Kolicina" SET DEFAULT 0;
ALTER TABLE public."tLokacijeDelova" ALTER COLUMN "DatumIVremeUnosa" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tOperacije" ALTER COLUMN "BezPostupka" SET DEFAULT false;
ALTER TABLE public."tOperacije" ALTER COLUMN "ZnacajneOperacijeZaZavrsen" SET DEFAULT false;
ALTER TABLE public."tOperacije" ALTER COLUMN "KoristiPrioritet" SET DEFAULT false;
ALTER TABLE public."tOperacije" ALTER COLUMN "PreskocivaOperacija" SET DEFAULT false;
ALTER TABLE public."tPDM" ALTER COLUMN "IDRN" SET DEFAULT 0;
ALTER TABLE public."tPDM" ALTER COLUMN "OperacijaPDM" SET DEFAULT 0;
ALTER TABLE public."tPDM" ALTER COLUMN "Komada" SET DEFAULT 0;
ALTER TABLE public."tPDM" ALTER COLUMN "DIVUnosa" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tPDM" ALTER COLUMN "DIVIspravke" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tPDM" ALTER COLUMN "SifraRadnika" SET DEFAULT 0;
ALTER TABLE public."tPLP" ALTER COLUMN "IDRN" SET DEFAULT 0;
ALTER TABLE public."tPLP" ALTER COLUMN "TezinaJed" SET DEFAULT 0;
ALTER TABLE public."tPLP" ALTER COLUMN "Komada" SET DEFAULT 0;
ALTER TABLE public."tPLP" ALTER COLUMN "DIVUnosa" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tPLP" ALTER COLUMN "DIVIspravke" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tPLP" ALTER COLUMN "SifraRadnika" SET DEFAULT 0;
ALTER TABLE public."tPND" ALTER COLUMN "IDRN" SET DEFAULT 0;
ALTER TABLE public."tPND" ALTER COLUMN "OperacijaPND" SET DEFAULT 0;
ALTER TABLE public."tPND" ALTER COLUMN "Komada" SET DEFAULT 0;
ALTER TABLE public."tPND" ALTER COLUMN "DIVUnosa" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tPND" ALTER COLUMN "DIVIspravke" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tPND" ALTER COLUMN "SifraRadnika" SET DEFAULT 0;
ALTER TABLE public."tRadnici" ALTER COLUMN "ProcenatZaObracun" SET DEFAULT 0;
ALTER TABLE public."tRadnici" ALTER COLUMN "Aktivan" SET DEFAULT true;
ALTER TABLE public."tRadnici" ALTER COLUMN "IDRadneJedinice" SET DEFAULT '0';
ALTER TABLE public."tRadnici" ALTER COLUMN "IDVrsteRadnika" SET DEFAULT 0;
ALTER TABLE public."tRadnici" ALTER COLUMN "DefiniseSaglasan" SET DEFAULT false;
ALTER TABLE public."tRadnici" ALTER COLUMN "DefiniseLansiran" SET DEFAULT false;
ALTER TABLE public."tRadnici" ALTER COLUMN "MultiNalog" SET DEFAULT false;
ALTER TABLE public."tRN" ALTER COLUMN "IDPredmet" SET DEFAULT 0;
ALTER TABLE public."tRN" ALTER COLUMN "Varijanta" SET DEFAULT 0;
ALTER TABLE public."tRN" ALTER COLUMN "BBDatumOtvaranja" SET DEFAULT (CURRENT_DATE::timestamp);
ALTER TABLE public."tRN" ALTER COLUMN "Komada" SET DEFAULT 1;
ALTER TABLE public."tRN" ALTER COLUMN "TezinaNeobrDela" SET DEFAULT 0;
ALTER TABLE public."tRN" ALTER COLUMN "IdentMaterijala" SET DEFAULT 0;
ALTER TABLE public."tRN" ALTER COLUMN "TezinaObrDela" SET DEFAULT 0;
ALTER TABLE public."tRN" ALTER COLUMN "StatusRN" SET DEFAULT false;
ALTER TABLE public."tRN" ALTER COLUMN "DIVUnosaRN" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tRN" ALTER COLUMN "DIVIspravkeRN" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tRN" ALTER COLUMN "SifraRadnika" SET DEFAULT 0;
ALTER TABLE public."tRN" ALTER COLUMN "Zakljucano" SET DEFAULT false;
ALTER TABLE public."tRN" ALTER COLUMN "PrnTimer" SET DEFAULT 0;
ALTER TABLE public."tRN" ALTER COLUMN "IDVrstaKvaliteta" SET DEFAULT 0;
ALTER TABLE public."tRN" ALTER COLUMN "Revizija" SET DEFAULT 'A';
ALTER TABLE public."tRN" ALTER COLUMN "IDPrimopredaje" SET DEFAULT 0;
ALTER TABLE public."tRN" ALTER COLUMN "IDCrtez" SET DEFAULT 0;
ALTER TABLE public."tRN" ALTER COLUMN "IDStatusPrimopredaje" SET DEFAULT 3;
ALTER TABLE public."tRN" ALTER COLUMN "SifraRadnikaPrimopredaje" SET DEFAULT 0;
ALTER TABLE public."tRNKomponente" ALTER COLUMN "BrojKomada" SET DEFAULT 1;
ALTER TABLE public."tSaglasanRN" ALTER COLUMN "IDRN" SET DEFAULT 0;
ALTER TABLE public."tSaglasanRN" ALTER COLUMN "Saglasan" SET DEFAULT false;
ALTER TABLE public."tSaglasanRN" ALTER COLUMN "DIVUnos" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tSaglasanRN" ALTER COLUMN "SifraRadnikaUnos" SET DEFAULT 0;
ALTER TABLE public."tSaglasanRN" ALTER COLUMN "DIVIspravke" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tStavkeRN" ALTER COLUMN "IDRN" SET DEFAULT 0;
ALTER TABLE public."tStavkeRN" ALTER COLUMN "Operacija" SET DEFAULT 0;
ALTER TABLE public."tStavkeRN" ALTER COLUMN "Tpz" SET DEFAULT 0;
ALTER TABLE public."tStavkeRN" ALTER COLUMN "Tk" SET DEFAULT 0;
ALTER TABLE public."tStavkeRN" ALTER COLUMN "TezinaTO" SET DEFAULT 0;
ALTER TABLE public."tStavkeRN" ALTER COLUMN "SifraRadnika" SET DEFAULT 0;
ALTER TABLE public."tStavkeRN" ALTER COLUMN "DIVUnosa" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tStavkeRN" ALTER COLUMN "DIVIspravke" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tStavkeRN" ALTER COLUMN "Prioritet" SET DEFAULT 100;
ALTER TABLE public."tStavkeRNSlike" ALTER COLUMN "IDStavkeRN" SET DEFAULT 0;
ALTER TABLE public."tTehPostupak" ALTER COLUMN "IDPredmet" SET DEFAULT 0;
ALTER TABLE public."tTehPostupak" ALTER COLUMN "Varijanta" SET DEFAULT 0;
ALTER TABLE public."tTehPostupak" ALTER COLUMN "PrnTimer" SET DEFAULT 0;
ALTER TABLE public."tTehPostupak" ALTER COLUMN "DatumIVremeUnosa" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public."tTehPostupak" ALTER COLUMN "SimbolRadnik" SET DEFAULT false;
ALTER TABLE public."tTehPostupak" ALTER COLUMN "SimbolPostupak" SET DEFAULT false;
ALTER TABLE public."tTehPostupak" ALTER COLUMN "SimbolOperacija" SET DEFAULT false;
ALTER TABLE public."tTehPostupak" ALTER COLUMN "ZavrsenPostupak" SET DEFAULT false;
ALTER TABLE public."tTehPostupak" ALTER COLUMN "IDRN" SET DEFAULT 0;
ALTER TABLE public."tTehPostupak" ALTER COLUMN "IDVrstaKvaliteta" SET DEFAULT 0;
ALTER TABLE public."tTehPostupak" ALTER COLUMN "DoradaOperacije" SET DEFAULT 0;
ALTER TABLE public."tVrsteRadnika" ALTER COLUMN "DodatnaOvlascenja" SET DEFAULT false;
ALTER TABLE public."UplatniRacuni" ALTER COLUMN "IDFirma" SET DEFAULT 0;
ALTER TABLE public."UplatniRacuni" ALTER COLUMN "Default" SET DEFAULT false;
ALTER TABLE public."UplatniRacuni" ALTER COLUMN "Rbr" SET DEFAULT 0;

-- === UNIQUE (kolone koje FK referišu a nisu same PK; Postgres zahtev) ===

ALTER TABLE public."R_Tarife" ADD CONSTRAINT "UQ_R_Tarife_Tarifa" UNIQUE ("Tarifa");
ALTER TABLE public."tOperacije" ADD CONSTRAINT "UQ_tOperacije_RJgrupaRC" UNIQUE ("RJgrupaRC");

-- === Strani ključevi ===

ALTER TABLE public."_RegAppsFiles" ADD CONSTRAINT "FK__RegAppsFiles__RegApps" FOREIGN KEY ("AppName") REFERENCES public."_RegApps" ("AppName");
ALTER TABLE public."_RegUsersApps" ADD CONSTRAINT "FK__RegUsersApps__RegApps" FOREIGN KEY ("AppName") REFERENCES public."_RegApps" ("AppName");
ALTER TABLE public."_RegUsersApps" ADD CONSTRAINT "FK__RegUsersApps__RegUsers" FOREIGN KEY ("RegUserID") REFERENCES public."_RegUsers" ("RegUserID");
ALTER TABLE public."BBDefUser" ADD CONSTRAINT "FK_BBDefUser_BBOdeljenja" FOREIGN KEY ("DefaultOD") REFERENCES public."BBOdeljenja" ("OD");
ALTER TABLE public."BBDefUser" ADD CONSTRAINT "FK_BBDefUser_BBOrgJedinice" FOREIGN KEY ("DefaultOJ") REFERENCES public."BBOrgJedinice" ("OJ");
ALTER TABLE public."Cenovnik" ADD CONSTRAINT "Cenovnik_FK00" FOREIGN KEY ("Sifra artikla") REFERENCES public."R_Artikli" ("Sifra artikla");
ALTER TABLE public."Cenovnik" ADD CONSTRAINT "Cenovnik_FK01" FOREIGN KEY ("Tarifa") REFERENCES public."R_Tarife" ("Tarifa");
ALTER TABLE public."Komitenti" ADD CONSTRAINT "FK_Komitenti_Prodavci" FOREIGN KEY ("Sifra prodavca") REFERENCES public."Prodavci" ("Sifra prodavca");
ALTER TABLE public."Komitenti" ADD CONSTRAINT "Komitenti_FK01" FOREIGN KEY ("IDVozac") REFERENCES public."Komitenti" ("Sifra");
ALTER TABLE public."Komitenti" ADD CONSTRAINT "Komitenti_FK02" FOREIGN KEY ("Vrsta sifre") REFERENCES public."Vrste sifara" ("Vrsta sifre");
ALTER TABLE public."KomponentePDMCrteza" ADD CONSTRAINT "FK_KomponentePDMCrteza_TrebaIDCrtez" FOREIGN KEY ("TrebaIDCrtez") REFERENCES public."PDMCrtezi" ("IDCrtez");
ALTER TABLE public."KomponentePDMCrteza" ADD CONSTRAINT "FK_KomponentePDMCrteza_ZaIDCrtez" FOREIGN KEY ("ZaIDCrtez") REFERENCES public."PDMCrtezi" ("IDCrtez");
ALTER TABLE public."MRP_PotrebeStavke" ADD CONSTRAINT "FK_MRP_PotrebeStavke_MRP_Potrebe" FOREIGN KEY ("IDPotreba") REFERENCES public."MRP_Potrebe" ("IDPotreba");
ALTER TABLE public."NacrtPrimopredaje" ADD CONSTRAINT "FK_NacrtPrim_Predmeti" FOREIGN KEY ("IDPredmet") REFERENCES public."Predmeti" ("IDPredmet");
ALTER TABLE public."NacrtPrimopredaje" ADD CONSTRAINT "FK_NacrtPrim_Projektant" FOREIGN KEY ("IDProjektant") REFERENCES public."tRadnici" ("SifraRadnika");
ALTER TABLE public."NacrtPrimopredaje" ADD CONSTRAINT "FK_NacrtPrimopredaje_StatusiNacrtaPrimopredaje" FOREIGN KEY ("IDStatusNacrtaPrimopredaje") REFERENCES public."StatusiNacrtaPrimopredaje" ("IDStatusNacrtaPrimopredaje");
ALTER TABLE public."NacrtPrimopredaje" ADD CONSTRAINT "FK_NP_IDGlavniCrtez_PDMCrtezi" FOREIGN KEY ("IDGlavniCrtez") REFERENCES public."PDMCrtezi" ("IDCrtez");
ALTER TABLE public."NacrtPrimopredajeStavke" ADD CONSTRAINT "FK_NacrtPrimStavke_NacrtPrim" FOREIGN KEY ("IDNacrtPrim") REFERENCES public."NacrtPrimopredaje" ("IDNacrtPrim");
ALTER TABLE public."NacrtPrimopredajeStavke" ADD CONSTRAINT "FK_NPS_RootCrtez" FOREIGN KEY ("IDGlavniCrtez") REFERENCES public."PDMCrtezi" ("IDCrtez");
ALTER TABLE public."PDM_Planiranje" ADD CONSTRAINT "FK_PDM_Planiranje_CrtezSklopa" FOREIGN KEY ("IDCrtezSklopa") REFERENCES public."PDMCrtezi" ("IDCrtez");
ALTER TABLE public."PDM_PlaniranjeStavke" ADD CONSTRAINT "FK_PDM_PlaniranjeStavke_CrtezNabavke" FOREIGN KEY ("IDCrtezNabavke") REFERENCES public."PDMCrtezi" ("IDCrtez");
ALTER TABLE public."PDM_PlaniranjeStavke" ADD CONSTRAINT "FK_PDM_PlaniranjeStavke_Plan" FOREIGN KEY ("IDPlan") REFERENCES public."PDM_Planiranje" ("IDPlan");
ALTER TABLE public."PDMCrtezi" ADD CONSTRAINT "FK_PDMCrtezi_StatusiCrteza" FOREIGN KEY ("IDStatusCrteza") REFERENCES public."StatusiCrteza" ("IDStatusCrteza");
ALTER TABLE public."PrimopredajaCrteza" ADD CONSTRAINT "FK_PPcr_PDMCrtezi" FOREIGN KEY ("IDCrtez") REFERENCES public."PDMCrtezi" ("IDCrtez");
ALTER TABLE public."PrimopredajaCrteza" ADD CONSTRAINT "FK_PPcr_Status" FOREIGN KEY ("IDStatusPrimopredaje") REFERENCES public."StatusiPrimopredaje" ("IDStatusPrimopredaje");
ALTER TABLE public."PrimopredajaPDFCrteza" ADD CONSTRAINT "FK_PrimopredajaPDFCrteza_PrimopredajaCrtetza" FOREIGN KEY ("IDPrimopredaje") REFERENCES public."PrimopredajaCrteza" ("IDPrimopredaje");
ALTER TABLE public."RobneStavkeMirror" ADD CONSTRAINT "FK_RSM_Dokument" FOREIGN KEY ("IDDok") REFERENCES public."RobnaDokumentaMirror" ("IDDok");
ALTER TABLE public."SklopoviPDMCrteza" ADD CONSTRAINT "FK_SklopoviPDMCrteza_Crtez" FOREIGN KEY ("IDCrtez") REFERENCES public."PDMCrtezi" ("IDCrtez");
ALTER TABLE public."SklopoviPDMCrteza" ADD CONSTRAINT "FK_SklopoviPDMCrteza_KoristiSeUIDCrteza" FOREIGN KEY ("KoristiSeUIDCrteza") REFERENCES public."PDMCrtezi" ("IDCrtez");
ALTER TABLE public."tLansiranRN" ADD CONSTRAINT "tLansiranRN_FK00" FOREIGN KEY ("IDRN") REFERENCES public."tRN" ("IDRN");
ALTER TABLE public."tLokacijeDelova" ADD CONSTRAINT "FK_tLokacijeDelova_Predmeti" FOREIGN KEY ("IDPredmet") REFERENCES public."Predmeti" ("IDPredmet");
ALTER TABLE public."tLokacijeDelova" ADD CONSTRAINT "FK_tLokacijeDelova_tPozicije" FOREIGN KEY ("IDPozicija") REFERENCES public."tPozicije" ("IDPozicije");
ALTER TABLE public."tLokacijeDelova" ADD CONSTRAINT "FK_tLokacijeDelova_tRadnici" FOREIGN KEY ("SifraRadnika") REFERENCES public."tRadnici" ("SifraRadnika");
ALTER TABLE public."tPDM" ADD CONSTRAINT "tPDM_FK00" FOREIGN KEY ("SifraRadnika") REFERENCES public."tRadnici" ("SifraRadnika");
ALTER TABLE public."tPDM" ADD CONSTRAINT "tPDM_FK01" FOREIGN KEY ("RJgrupaRC") REFERENCES public."tOperacije" ("RJgrupaRC");
ALTER TABLE public."tPDM" ADD CONSTRAINT "tPDM_FK02" FOREIGN KEY ("IDRN") REFERENCES public."tRN" ("IDRN");
ALTER TABLE public."tPLP" ADD CONSTRAINT "tPLP_FK00" FOREIGN KEY ("SifraRadnika") REFERENCES public."tRadnici" ("SifraRadnika");
ALTER TABLE public."tPLP" ADD CONSTRAINT "tPLP_FK01" FOREIGN KEY ("RJgrupaRC") REFERENCES public."tOperacije" ("RJgrupaRC");
ALTER TABLE public."tPLP" ADD CONSTRAINT "tPLP_FK02" FOREIGN KEY ("IDRN") REFERENCES public."tRN" ("IDRN");
ALTER TABLE public."tPND" ADD CONSTRAINT "tPND_FK00" FOREIGN KEY ("SifraRadnika") REFERENCES public."tRadnici" ("SifraRadnika");
ALTER TABLE public."tPND" ADD CONSTRAINT "tPND_FK01" FOREIGN KEY ("RJgrupaRC") REFERENCES public."tOperacije" ("RJgrupaRC");
ALTER TABLE public."tPND" ADD CONSTRAINT "tPND_FK02" FOREIGN KEY ("IDRN") REFERENCES public."tRN" ("IDRN");
ALTER TABLE public."tPristupMasini" ADD CONSTRAINT "tPristupMasini_FK00" FOREIGN KEY ("RJgrupaRC") REFERENCES public."tOperacije" ("RJgrupaRC");
ALTER TABLE public."tPristupMasini" ADD CONSTRAINT "tPristupMasini_FK01" FOREIGN KEY ("SifraRadnika") REFERENCES public."tRadnici" ("SifraRadnika");
ALTER TABLE public."tRN" ADD CONSTRAINT "FK_tRN_SifraRadnikaPrimopredaje_tRadnici" FOREIGN KEY ("SifraRadnikaPrimopredaje") REFERENCES public."tRadnici" ("SifraRadnika");
ALTER TABLE public."tRN" ADD CONSTRAINT "FK_tRN_StatusiPrimopredaje" FOREIGN KEY ("IDStatusPrimopredaje") REFERENCES public."StatusiPrimopredaje" ("IDStatusPrimopredaje");
ALTER TABLE public."tRN" ADD CONSTRAINT "FK_tRN_tRadnici" FOREIGN KEY ("SifraRadnika") REFERENCES public."tRadnici" ("SifraRadnika");
ALTER TABLE public."tRN" ADD CONSTRAINT "FK_tRN_tVrsteKvalitetaDelova" FOREIGN KEY ("IDVrstaKvaliteta") REFERENCES public."tVrsteKvalitetaDelova" ("IDVrstaKvaliteta");
ALTER TABLE public."tRNKomponente" ADD CONSTRAINT "FK_tRNKomponente_ParentRN" FOREIGN KEY ("IDRN") REFERENCES public."tRN" ("IDRN");
ALTER TABLE public."tRNNDKomponente" ADD CONSTRAINT "FK_tRNNDKomponente_R_Artikli" FOREIGN KEY ("SifraArtikla") REFERENCES public."R_Artikli" ("Sifra artikla");
ALTER TABLE public."tRNNDKomponente" ADD CONSTRAINT "FK_tRNNDKomponente_RN" FOREIGN KEY ("IDRN") REFERENCES public."tRN" ("IDRN");
ALTER TABLE public."tSaglasanRN" ADD CONSTRAINT "tSaglasanRN_FK00" FOREIGN KEY ("IDRN") REFERENCES public."tRN" ("IDRN");
ALTER TABLE public."tStavkeRN" ADD CONSTRAINT "tStavkeRN_FK00" FOREIGN KEY ("SifraRadnika") REFERENCES public."tRadnici" ("SifraRadnika");
ALTER TABLE public."tStavkeRN" ADD CONSTRAINT "tStavkeRN_FK01" FOREIGN KEY ("RJgrupaRC") REFERENCES public."tOperacije" ("RJgrupaRC");
ALTER TABLE public."tStavkeRN" ADD CONSTRAINT "tStavkeRN_FK02" FOREIGN KEY ("IDRN") REFERENCES public."tRN" ("IDRN");
ALTER TABLE public."tStavkeRNSlike" ADD CONSTRAINT "FK_tStavkeRNSlike_tStavkeRN" FOREIGN KEY ("IDStavkeRN") REFERENCES public."tStavkeRN" ("IDStavkeRN");
ALTER TABLE public."tTehPostupak" ADD CONSTRAINT "FK_tTehPostupak_tRadnici" FOREIGN KEY ("SifraRadnika") REFERENCES public."tRadnici" ("SifraRadnika");
ALTER TABLE public."tTehPostupakDokumentacija" ADD CONSTRAINT "FK_tTehPostupakDokumentacija_tTehPostupak" FOREIGN KEY ("IDPostupka") REFERENCES public."tTehPostupak" ("IDPostupka");
ALTER TABLE public."UplatniRacuni" ADD CONSTRAINT "FK_UplatniRacuni_UplatniRacuni" FOREIGN KEY ("ID") REFERENCES public."UplatniRacuni" ("ID");
